fedora-copr/copr

dist-git/dist_git/dist_git_importer.py
Mock(-scm) expects the cloned directory to has the same name as the package
it's building. To make sure it is so we explicitly pass the package name to
git clone as a destination directory name.
This allows (amont other things) to have a single git repo for multiple spec
files.
=> [copr-dist-git] Don't assume the SCM repo has the same name as the package

python/copr/client_v2/handlers.py
in python3 map() does not return list
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1327607
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> handlers: use list() after map() for chroots

HACKING
There was a typo in alembic command invocation.
=> [doc] Fix a typo in HACKING

frontend/coprs_frontend/coprs/templates/coprs/copr.repo
When using Zypper with copr repos, this needs to be added so that Zypper can properly consume the repository metadata.
=> [frontend] Add flags for Zypper to accept copr repositories

backend/backend/mockremote/builder.py
Braces need to be escaped in order not to be interpreted as character
class by Ansible.
CC @msimacek
=> Backend: Fix chroot_setup_cmd regex for custom chroot

frontend/coprs_frontend/coprs/templates/coprs/create_module.html
=> Fix a typo

backend/units/copr-backend.target, dist-git/copr-dist-git.service
Currently we do this in ansible
service: name="{{ item }}" enabled=yes state=started
with_items:
- redis       # TODO: .service in copr-backend should depend on redis
which isn't the best solution.
=> backend, distgit: require redis.service to be started

beaker-tests/DockerTestEnv/Dockerfile
In order to be consistent with our docker-compose images. Also the image on dockerhub is not updated as frequently and currently, the F37 image points to F38 for some reason.
=> beaker-tests: use F37 image for DockerTestEnv from Fedora registry

backend/copr-backend.spec, backend/copr_backend/background_worker.py, common/copr_common/background_worker.py, common/python-copr-common.spec, dist-git/copr-dist-git.spec
By always calling the self._wm_started() method.  This needs to be done in the parent BackgroundWorker class so we don't forget about it in inheriting classes -> and it needs to be done ASAP.  To keep the order of things to be done (first call _wm_started(), then redirect logs to redis for the backend side, and then handle_task()) - there's now a new method preparations_for_manager() which is called after _wm_started() but before handle_task().
=> backend, common, dist-git: correct background worker start

backend/copr_backend/sign.py, backend/tests/test_sign.py
From Panu's statement in #2379:
v3 signatures which obs-signd currently creates by default were obsolete in 1998 already, but needed for interoperability in the early millennium.  Everything from the last 15 years supports v4 signatures, lets get on with the times.
This requires at obs-signd 2.5.2 (released in 2018) or newer. Perhaps worth noting that the -4 switch is undocumented in obs-sign man pages.
For more background, see
https://bugzilla.redhat.com/show_bug.cgi?id=2141686 and openSUSE/obs-sign#43
Closes: #2379
Closes: #2383
=> backend: use OpenPGP v4 signatures

frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py
Fix #2398
The original code didn't cover a case when "repos" are in the `source_json_dict` but its value is `None`.
=> frontend: fix traceback when repos are not set

backend/copr_backend/background_worker_build.py
There's no need to fail the build on this place, with a weird error message users wouldn't anyway understand.
If the packages had wrong signatures, following builds would at least find this problem anyway very quickly because the repos have gpgcheck=1.
Fixes: #2388
=> backend: list the built RPMs with rpm --nosignature

backend/units/copr-backend-log.service, backend/units/copr-backend.target, dist-git/copr-dist-git.service
On top of Requires=, we need also After= so redis is started first. Long term (for the OpenShift scenario) we should make the Redis client connections resilient against the temporary Redis server outages.
The copr-backend.target depends on three services which have the dependency resolved between each other (actions/builds depend on log, log depends on redis).
With copr-dist-git.service it is much simpler, we just depend on redis.service.
=> backend, dist-git: start services after redis.service

doc/how_to_upgrade_persistent_instances.rst
The LetsEncrypt certificates need to be copied form old server => batcave => new server.  We need to assure the backed-up certificates are not too old.
Also, DistGit is now storing all the data, including logs, on one (large) volume.
=> doc: notes for the yesterday's F35 => F37 move

cli/copr_cli/main.py, cli/tests/test_cli.py, frontend/coprs_frontend/coprs/forms.py, frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py, python/copr/v3/proxies/project.py
The appstream-builder (the utility used for modifying metadata) is very I/O demanding.  It is known to fail even for not really huge projects.
Related: https://github.com/hughsie/appstream-glib/issues/301
The tool is also about to be replaced by appstream-generator or alike: https://github.com/rpm-software-management/createrepo_c/issues/75
Relates: #2358
Fixes: #2419
=> frontend, cli, python: disable appstream by default

docker/backend_httpd/files/etc/nginx/conf.d/copr-be.conf, kubernetes/kustomize/backend.yaml, kubernetes/kustomize/kustomization.yaml
Since the centos-nginx server's default mine type is `octet-stream`, this PR will make the `backend-httpd` container works more likely offical copr instance, all textual file include `.log`, `.log.gz`, `.json`, `.spec` etc, can be displayed in browser directly.
Signed-off-by: lichaoran <pkwarcraft@gmail.com>
=> backend_httpd: make textual file readable through browser

frontend/coprs_frontend/coprs/static/copr.css
Fix RHBZ 2152268
Our v3 bootstrap supports `.table-hover` class for tables but its has a blue color which is too inconsistent with the rest of our colorscheme. I am adding the hover via CSS and using the gray color that is used by bootstrap v4.
=> frontend: add hover for table rows

cli/copr_cli/monitor.py
=> cli: use the --dirname parameter for copr-cli monitor

kubernetes/kustomize/resalloc.yaml
The new pod will hangs in attaching the pvs since the old one still holding it.
Signed-off-by: lichaoran <pkwarcraft@gmail.com>
=> fix: pod strategy set to recreate as attached volume is ReadWriteOnce

doc/how_to_release_copr.rst, frontend/coprs_frontend/commands/warning_banner.py, frontend/coprs_frontend/coprs/constants.py, frontend/coprs_frontend/coprs/context_processors.py, frontend/coprs_frontend/coprs/templates/banner-include.html, frontend/coprs_frontend/manage.py
=> frontend: add commands for adding and removing warning banner

backend/copr_backend/actions.py, backend/copr_backend/background_worker_build.py, backend/copr_backend/helpers.py, backend/copr_backend/msgbus.py, backend/copr_backend/sign.py, backend/run/copr_sign_unsigned.py, backend/tests/test_helpers.py, rpmbuild/copr_rpmbuild/providers/spec.py
I found some builds that failed for a strange reason, e.g.
https://copr.fedorainfracloud.org/coprs/frostyx/fedora-review-2133080-python-nss/build/5198485/
Copy-pasting a relevant part from `backend.log`
```
[2023-01-03 22:45:58,230][  INFO][PID:4041220] Going to sign pkgs from source: 5198485 in chroot: /var/lib/copr/public_html/results/frostyx/fedora-review-2133080-python-nss/srpm-builds
[2023-01-03 22:45:58,230][  INFO][PID:4041220] Calling '/bin/sign -u frostyx#fedora-review-2133080-python-nss@copr.fedorahosted.org -p' (attempt #1)
[2023-01-03 22:45:58,240][WARNING][PID:4041220] Command '/bin/sign -u frostyx#fedora-review-2133080-python-nss@copr.fedorahosted.org -p' failed with: unknown key: frostyx#fedora-review-2133080-python-nss@copr.fedorahosted.org
[2023-01-03 …
```
=> Submitting packages with URL encoded characters

rpmbuild/main.py
=> rpmbuild: don't print traceback for 404 errors on SRPM download

frontend/coprs_frontend/coprs/logic/users_logic.py
Fix #2448
The tilde doesn't make any sense, it had to be a copy-paste error or something. According to the documentation
https://docs.sqlalchemy.org/en/20/core/operators.html tilde means `NOT`, so we were returning users without projects, not users with projects.
=> frontend: fix homepage user count

frontend/copr-frontend.spec, frontend/requirements.txt
This is not needed since we removed APIv2 354441eaeeff929720d584df7e07e32892c1eb06.
=> frontend: don't depend on flask-restful

README.md
This reverts commit ebfa21d5cc038136cb8f05da3dc36e2a99916083.
Because of https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/ LGTM has been replaced code scanning feature directly in GH.
=> Revert "Add badges for LGTM.com"

frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/templates/coprs/show/group.html
Other Copr instances might want to point somewhere else then FAS.
=> frontend: customizable group link to FAS

rpmbuild/copr-rpmbuild.spec, rpmbuild/copr_rpmbuild/helpers.py, rpmbuild/tests/test_base.py
how copr_rpmbiuld is run? If I throw there a sleep (as I does) do I stop building only for one VM (and one user) or for everybody?
Fix #2394
=> re-try git clone when copr-dist-git is temporarily down

backend/copr_backend/job.py, frontend/copr-frontend.spec, frontend/requirements.txt, python/python-copr.spec, python/setup.py
Since we dropped APIv1 and APIv2, we don't use marshmallow (at least not directly) now.  The explicit dependency on the lib was just a leftover.
=> frontend, backend, python: drop the unneeded marshmallow dep

frontend/coprs_frontend/alembic/script.py.mako
I remember seeing pylint errors in newly generated migration scripts. I am copy-pasting the template installed from `python3-alembic-1.7.7-3.fc37.noarch`.
=> frontend: update alembic migration template

frontend/copr-frontend.spec, frontend/coprs_frontend/coprs/logic/batches_logic.py
Fix #2107
The said reproducer didn't work for me. I used this one:
parallel copr build-package @copr/foo --nowait --background \
--after-build-id 123  --name \
::: $(for i in {1..50}; do echo "copr-cli"; done)
=> frontend: fix batches race logic by adding locks

docker-compose.shell.yaml
Here is how I use it
http://frostyx.cz/posts/copr-docker-compose-without-supervisord#keygen
=> docker: add keygen-httpd service to docker-compose.shell.yaml

backend/copr_backend/background_worker_build.py, backend/copr_backend/frontend.py, backend/tests/test_background_worker_build.py, frontend/coprs_frontend/coprs/exceptions.py, frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py
Fix #2390
First, take a look at the frontend change. The
`BuildsLogic.get_srpm_build_task` never raises an exception. It returns `None` for non-existing tasks instead. The route therefore returns 200 status code even for non-existing tasks, and simply returns `nil`. I am changing this to return 404 instead.
This prompted the backend changes because exceptions started appearing.
=> frontend, backend: fix traceback for non-existing tasks

frontend/coprs_frontend/coprs/views/webhooks_ns/webhooks_general.py
It turns out non-json payload was never actually handed-over to a custom script.  This was caused by the artificial request.json check in the HookContentStorage.__init__ method.  But with the previous Flask versions we were at at least able to successfully submit the custom webhook build even with an empty payload without specified content type.
After the migration to F37 with new Flask the check for request.json started raising the exception 400 for empty payloads (causing #2416):
Did not attempt to load JSON data because the request Content-Type
was not 'application/json'
The JSON check is now replaced with request.get_data() which is a safe call in any case (form submitted, json data, uploaded file).
Fixes: #2416
=> frontend: allow uploading artificial payload in custom webhook

keygen/src/copr_keygen/logic.py, keygen/tests/test_logic.py
Beaker tests revealed some bugs in the keygen email validation. It
failed for projects with dashes and projects with dots in their
names.
The culprit was wrongly placed dash character in the regex, it needs
to be at the beginning otherwise it is interpreted as a range.
=> keygen: fix validation for projects with dash in their name

.tito/releasers.conf
=> releng: don't build for F35 anymore

backend/tests/test_modifyrepo.py
To me it looks like a test issue, not a bug in the code. We should fix it after the release. The errors looks like this:
DEBUG    root:helpers.py:44 Executing: dnf repoquery
--repofrompath=prunerepo_query,/tmp/copr-backend-test-sinye9kv/john/empty/fedora-rawhide-x86_64
--repo=prunerepo_query --refresh --queryformat=%{location} --quiet
--setopt=skip_if_unavailable=False --latest-limit=1
DEBUG    root:helpers.py:51 Command error output: Error: Cannot
create repo destination directory
"/var/cache/yum/prunerepo_query-a8d5eb167f90766c": Permission
denied
Maybe the repoquery needs to be explicitly called with --tempcache?
=> backend: skip the test_run_prunerepo test because of Koji

rpmbuild/copr-rpmbuild.spec
=> rpmbuild: add runtime dependency for python-backoff

frontend/coprs_frontend/coprs/forms.py
The value is actually a string taken from database, there's no need to use ", ".join().
=> frontend: fix the "Modules:" form widget

doc/how_to_release_copr.rst
- Add and remove outage banner with the rest of the announcement steps
- Remove copr-rest-api documentation page, it doesn't exist anymore
- Use `copr-frontend` instead of `manage.py`
=> doc: some postrelease fixes after 2023-01-25 release

backend/copr_backend/actions.py, backend/copr_backend/helpers.py, backend/tests/test_helpers.py
This seems like a low-hanging fruit.  We never touch the generated RPMs, except when we want to re-sign them.  This happens only in accidental or exceptional situations, and those files would be re-signed multiple times (so we should be careful about race-conditions).
Fixes: #971
=> frontend: hardlink in rawhide_to_release

frontend/coprs_frontend/coprs/logic/coprs_logic.py
We got a report that we accidentally branched `fedora-38-armhfp` chroot. That's because we don't use the `active_only` parameter and therefore branch inactive `fedora-rawhide-armhfp`.
=> Don't branch armhfp chroots

backend/copr-backend.spec, frontend/copr-frontend.spec
It is a leftover, we are using modulemd-tools for modularity things, so let it figure out the dependencies.
=> frontend, backend: remove libmodulemd1 dependency

keygen/copr-keygen.spec
copr-keygen.spec uses %defattr for copr-signer, and we mistakenly included the logrotate drop-in file there, new logrotate started to dislike this, per logrotate error:
error: Ignoring copr-keygen because the file owner is wrong (should
be root or user with uid 0).
The cron.daily script, if moved up a bit in the %files section doesn't need the %attr override either.
While on it, the sudoers dropin config shouldn't be '(noreplace)'.  We want to maintain/replace the file via RPM updates.
=> keygen: fix config files installation pattern

doc/custom_source_method.rst, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py, rpmbuild/bin/copr-sources-custom, rpmbuild/copr_rpmbuild/providers/custom.py
See #557
That RFE requested mainly package name, and additionally project name and owner name. I am adding only the last two. The package name will be hard to implement because we don't have its value in copr-rpmbuild. Moreover, we can't even send it from the frontend because when doing Packages > some package > Rebuild, we don't save the package <-> build relationship to the database. It is saved only after the SRPM is built.
=> Define some copr-specific environment variables for custom method

cli/copr_cli/build_config.py, cli/tests/test_mock_config.py
For Mock, config_opts['dnf.conf'] option is just an alias to the config_opts['yum.conf'] option.  Since 2020:
https://github.com/rpm-software-management/mock/commit/5d620ad326da0f656883f090c588bcfe36e92858
=> cli: simplify `mock-config` output

build_aux/Containerfile.unittest, build_aux/per-subdir-makefile
this is just my personal hack that I am using to unittest in containers. (bcs I don't want to install many packages in my system that I won't use)
=> build_aux: Add hack for unittesting in container

frontend/coprs_frontend/coprs/templates/_helpers.html
`openEuler` is our canonical name ：）
=> use openEuler as the canonical name

rpmbuild/copr_distgit_client.py, rpmbuild/etc/copr-distgit-client/default.ini
This is useful to easily clone package "Foo" from DistGit "Bar", without the need to recall the clone_url from head.  This isn't used by automation now, even though it could be in the future.
=> rpmbuild: dist-git-client: add basic "clone" method

frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_builds.py
Previously we somewhat "faked" the user who is requesting build removals in the 'manage.py clean-old-builds' cron task.  That was faked to the "build.copr.user" which - for the group projects - might not be part of the group anymore and the pedantic check from a4e7a5aa467cad6132eb9d00170 stops us.
Newly, for automation task, we can use "automation_user=str()" argument that will effectively disable the user.can_build_in() check.
While on it, tweak the logging and error reporting a bit so there's is more obvious what is going on.
Fixes: #2523
=> frontend: allow automation (cron) to remove builds

rpmbuild/copr_rpmbuild/helpers.py, rpmbuild/tests/test_distgit.py
There's no ambiguity when committish we are switching to matches both filename/direname or branch name.
Fixes: #2566
=> rpmbuild: use 'git switch', not 'git checkout'

backend/copr-backend.spec, backend/copr_backend/msgbus.py
#2589 My thoughts stay straightforward, just make the copr_messaging and fedmsg into weak dependency...
=> make copr_messaging optional

backend/copr_backend/constants.py, backend/run/copr-repo, backend/tests/test_modifyrepo.py
dnf and yum system don't need to create sqlite database since dnf and yum no longer utilize them.
Although there are some systems that still require --database option. Yum3 used sqlite data so system like RHEL <= 7 and EPEL <= 7 still require --database option.
for more detailed reasoning of the --database exception please refer to: https://github.com/fedora-copr/copr/issues/1171
Fixes #1171
=> backend: run createrepo without --database

beaker-tests/Sanity/copr-cli-basic-operations/build-spec.sh, cli/copr_cli/main.py, cli/tests/test_cli.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_permissions.py, python/copr/v3/proxies/project.py
Fix #134
Tested for both non-existing project and someone else's project that I don't have permissions to.
We can easily drop the `self.client.base_proxy.auth_check()` from CLI because there is `@requires_api_auth` decorator on the function.
=> Make sure user can build in the project before uploading SRPM

frontend/copr-frontend.spec
We do not have fedora-messaging in openEuler, so change fedora-messaging as a optional runtime-requirement in frontend.
=> Make fedora-messaging  optional in frontend

frontend/coprs_frontend/config/copr_unit_test.conf, frontend/coprs_frontend/tests/coprs_test_case.py, frontend/coprs_frontend/tests/test_commands/test_notify_outdated_chroots.py, frontend/coprs_frontend/tests/test_commands/test_rawhide_to_release.py, frontend/coprs_frontend/tests/test_exceptions.py, frontend/coprs_frontend/tests/test_logic/test_batch_logic.py, frontend/coprs_frontend/tests/test_logic/test_complex_logic.py, frontend/coprs_frontend/tests/test_logic/test_copr_dirs_logic.py, frontend/coprs_frontend/tests/test_logic/test_coprs_logic.py, frontend/coprs_frontend/tests/test_logic/test_modules_logic.py, frontend/coprs_frontend/tests/test_logic/test_outdated_chroots_logic.py, frontend/coprs_frontend/tests/test_models.py, frontend/coprs_frontend/tests/test_views/test_backend_ns/test_backend_general.py, frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py
Drop the @new_app_context, we are creating a new app context for each test-case, and "pushing" it to the stack.
Also, recording SQL queries is now not ON by default, therefore setting SQLALCHEMY_RECORD_QUERIES to True.
Fixes: #2606
=> frontend: test compat with flask-sqlalchemy 3+

frontend/coprs_frontend/coprs/templates/project_info.html
We prefer GitHub issues and going to migrate all Bugzilla tickets soon.
=> frontend: change footer links from Bugzilla to GitHub

dist-git/tests/test_crazy_merging.py
new version of python-rpkg introduced unexpected behavior of commit
where it commits empty commit by default. This causes a bug if multiple
importing of a package happens in copr and the latter import of a
package is without any change, the following `commit` will make a new
commit hash because it allows empty commits by default.
I created an issue about it in rpkg. See
https://pagure.io/rpkg/issue/677
in the meantime the temporary solution of this is to downgrade
rpk package so we can release copr. Once this issue is resolved
remove the version specification from python3-rpkg package.
=> dist-git: downgrade python-rpkg to version 1.65

frontend/coprs_frontend/coprs/__init__.py, frontend/coprs_frontend/coprs/helpers.py, frontend/coprs_frontend/coprs/logic/complex_logic.py, frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_rpmrepo.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py, frontend/coprs_frontend/tests/coprs_test_case.py, frontend/coprs_frontend/tests/test_apiv3/test_rpmrepo.py, frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py
The new route provides all the necessary info needed to let the rest of the "repofile" creation task on DNF5 Copr plugin.  The route lists all the available CoprDirs, CoprChroots (even soon to be deleted) and dependencies.
The route contains seemingly useless parts like <dirname> and <name_release>.  These are only needed to keep the repo downloading statistics working with DNF5.
=> frontend: for-DNF5 API rpmrepo route

dist-git/tests/test_crazy_merging.py
new release of python-rpkg 1.66-5 introduces new bugs that breaks our tests.
=> dist-git: skip tests that python3-rpkg breaks

frontend/coprs_frontend/coprs/templates/api.html
Users are often confused and does not expect that when they log in this page change. Despite it is clearly written here. Let show the config and mask the values.
=> frontend: show API config even for not logged users

.github/workflows/python-diff-lint.yml
It looked like:
You have successfully added a new vcs-diff-lint configuration
.github/workflows/python-diff-lint.yml:python-lint-job. As part of
the setup process, we have scanned this repository and found no
existing alerts. In the future, you will see all code scanning
alerts on the repository Security tab.
The reason was that GitHub assumed that every single pull-request actually *newly* enabled the vcs-diff-lint action.  When we define also the 'push' action, the assumption no longer applies (sorta GitHub bug, not sure).
Relates: https://github.com/fedora-copr/vcs-diff-lint-action/pull/16
Relates: redhat-plumbers-in-action/differential-shellcheck#215
=> ci: avoid the ubiquitous github-code-scanning message

rpmbuild/copr_rpmbuild/helpers.py, rpmbuild/tests/test_distgit.py
Fix #2655
See #2566
See #2594
Close #2656
=> rpmbuild: use git checkout instead of switch but ignore files

messaging/copr_messaging/schema.py, messaging/copr_messaging/tests/test_schema.py
Previously, `BuildChrootStartedV1StompDontUse` didn’t and thus failed to set `app_name`, which made FMN fall back to the toplevel namespace of the message topic (lowercase `copr`), which in turn caused it to use both variations both in the user interface and when filtering messages (which warrants a fix of its own, see fedora-infra/fmn#854).
=> Derive all message classes from _CoprMessage

rpmbuild/copr_rpmbuild/helpers.py
We want to retry only git clone when exception happens because when `git clone succeeds but later `git checkout` fails then it will try to clone repo again which will fail in 100% times.
Fixes #2657
=> rpmbuild: retry only git clone without checkouting

backend/copr_backend/background_worker_build.py, backend/copr_backend/job.py, backend/tests/test_background_worker_build.py, rpmbuild/main.py
This will generate something like
```
You can reproduce this build on your computer by running:
dnf install copr-rpmbuild
/usr/bin/copr-rpmbuild --srpm --task-url https://copr.stg.fedoraproject.org/backend/get-srpm-build-task/2913535
```
at the beginning of the builder-live.log
=> Show users how to reproduce builds locally

rpmbuild/copr_rpmbuild/providers/scm.py, rpmbuild/tests/test_scm.py
=> fix: we should set git.safe_directory as repo rootdir

frontend/copr-frontend.spec, frontend/coprs_frontend/coprs/logic/batches_logic.py, rpmbuild/copr-rpmbuild.spec, rpmbuild/copr_rpmbuild/helpers.py
Do not merge until https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2023-995ddb45a1 is pushed into stable
Fix #2470
=> rpmbuild, frontend: add loggs to python-backoff decorator

frontend/copr-frontend.spec, frontend/coprs_frontend/coprs/__init__.py, frontend/coprs_frontend/coprs/error_handlers.py, frontend/coprs_frontend/coprs/templates/api.html, frontend/coprs_frontend/coprs/views/apiv3_ns/__init__.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_general.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_packages.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_project_chroots.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema.py
=> frontend: OpenAPI first steps

frontend/coprs_frontend/coprs/views/misc.py
Seems like something changed in the Fedora OpenID service, and that the second /login/ route request coming from the service to us is newly done as POST (not GET).
Closes: #2696
=> frontend: accept the OpenID response as a POST request

doc/raid_on_backend.rst
On both STG and production, the label is named `copr-repo` not `copr-data`:
[root@copr-be-dev ~][STG]# ls /dev/disk/by-label/copr*
/dev/disk/by-label/copr-repo
[root@copr-be ~][PROD]# ls /dev/disk/by-label/copr*
/dev/disk/by-label/copr-repo
=> doc: fix typo, the backend data label is named copr-repo

docker/frontend/Dockerfile, docker/frontend/files/etc/copr/copr.conf, frontend/copr-frontend.spec, frontend/coprs_frontend/config/copr.conf, frontend/coprs_frontend/config/copr_devel.conf, frontend/coprs_frontend/coprs/__init__.py, frontend/coprs_frontend/coprs/auth.py, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/context_processors.py, frontend/coprs_frontend/coprs/oidc.py, frontend/coprs_frontend/coprs/views/misc.py
The first PR for #2422 
1. add some config items for OpenID Connect
2. OpenID Connect supported is a opt-in feature
3. Integrated with authlib
Fixes #2422
=> add support for OIDC

frontend/coprs_frontend/coprs/views/apiv3_ns/schema.py
Through `runtest-module-hotfixes.sh` I found out that I forgot to add the module_hotfixes field and therefore it is missing from the `copr-cli mock-config` output.
=> frontend: add module_hotfixes to Repo schema

beaker-tests/Sanity/copr-cli-basic-operations/runtest.sh
The build fails with:
Out of memory allocating 671088640 bytes!
qemu: uncaught target signal 6 (Aborted) - core dumped
Already reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=2152259
The bug likely won't be fixed since F36 is now EOL, and at the same time armhfp support ended with F36.
=> beaker-tests-sanity: don't test armhfp builds anymore

common/python-copr-common.spec
ADD build supported in openEuler env, as openEuler use python3 as default
=> fix: common build failed in openEuler

cli/copr_cli/main.py
Per IRC discussion:
> <JensPetersen[m]>  I was trying to work out where `-r CHROOTS` "comes"
>                    from in `copr --help` say
> <JensPetersen[m]>  Does it accept comma separation?
> <JensPetersen[m]>  I wonder if -r CHROOT wouldn't be less confusing?
I agree, the -r/--chroot parameter does take only one value. The correct way to provide multiple values is to repeat the parameter.
=> cli: show CHROOT in help output instead of CHROOTS

dist-git/tests/test_crazy_merging.py
with newer version of pytest, the `skip` method from unittest stops working well with pytest
=> dist-git: use `skip` for skipping tests from pytest

build_aux/Containerfile.unittest, build_aux/per-subdir-makefile
update of make targets I use for unit testing in containers
=> build_aux: don't recreate testing image every time new test is launched

backend/copr-backend.spec, backend/copr_backend/background_worker_build.py, backend/copr_backend/helpers.py, backend/tests/test_background_worker_build.py, rpmbuild/copr_rpmbuild/helpers.py, rpmbuild/main.py
I am wondering whether we want to use information from spec file to name the SRPM? This means that SRPM name would be `example-1.0.14-1.src.rpm` instead of `example-1.0.14-1.fc37.src.rpm`
Fixes #1701
=> get info about build from SRPM's spec file

backend/copr_backend/helpers.py
The expanded_{epoch,version,reklease} attributes are all dynamic properties that can potentially raise exceptions.
=> backend: move all python-specfile stuff into try-except

rpmbuild/copr-rpmbuild.spec
This PR make tito build works in openEuler chroot:
1. some packages not exsted in openEuler so we exclude
2. some packages have a different name in openEuler
3. we donot have a dnf5 for now
=> rpmbuild: supported in openeuler

frontend/coprs_frontend/coprs/logic/packages_logic.py
Previously we just dropped ".git" suffix from git_cloneurl before comparison, but not the trailing slashes.  We also did just 'rstrip(".git")', which would also remove strings like "tig.git", potentially leading false-positive matches.
Fixes: #2722
=> frontend: better clone_url matching on webhooks

doc/user_documentation.rst, doc/user_documentation/reproducing_builds.rst
=> doc: how to reproduce builds

backend/copr_backend/background_worker_build.py, backend/copr_backend/frontend.py, backend/tests/test_background_worker_build.py, beaker-tests/Sanity/copr-cli-basic-operations/runtest-exclusivearch.sh, frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py, rpmbuild/copr-rpmbuild.spec, rpmbuild/copr_rpmbuild/automation/__init__.py, rpmbuild/copr_rpmbuild/automation/fedora_review.py, rpmbuild/copr_rpmbuild/automation/rpm_results.py, rpmbuild/copr_rpmbuild/automation/srpm_results.py, rpmbuild/copr_rpmbuild/helpers.py, rpmbuild/main.py
=> Skip excluded architectures

dist-git/run/copr-dist-git-refresh-cgit
In Fedora Copr, it goes from 550M to 94M.  This minimizes the issues with cgit.  The additional metadata were default, or just stub, so we can live with that.
Also, don't use `cat <<EOF` pattern to avoid unnecessary fork() calls by shell, use echo build-tin.
Fixes: #2410
=> dist-git: make the cgitrc include file smaller

frontend/copr-frontend.spec
Some of the python packages have different name in openEuler, so i switch to `python3dist(xxx)`
=> frontend: support building in openEuler

frontend/coprs_frontend/commands/failed_to_succeeded_stats.py, frontend/coprs_frontend/manage.py
=> frontend: add failed-to-succeeded-stats command

dist-git/copr-dist-git.spec, dist-git/copr_dist_git/package_import.py, dist-git/tests/test_crazy_merging.py
this PR is an attempt to shut down our CI problems with pyrpkg
`dist-git: refresh pyrpkg.Commands after import_srpm` commit - WDYT? this shouldn't be a problem for us from the efficiency side
after merging this, don't forget to merge https://pagure.io/fedora-infra/ansible/pull-request/1386
Fixes #2608 
Fixes #2317
=> Fix our dist-git CI

cli/copr_cli/main.py, frontend/coprs_frontend/coprs/forms.py
=> frontend, cli: make pyp2spec the default PyPI spec generator

.packit.yaml, cli/copr-cli.spec
This allows separating a package definition and a Packit job definition. Also, we can now work with multiple packages of this repository.
This pull request is a cleanup version of #2591.
=> Use monorepo setup for Packit

cli/copr-cli.spec, cli/setup.py, python/python-copr.spec, python/setup.py
PR https://github.com/fedora-copr/copr/pull/2812 removed the last usage of future from the project.
=> Drop dependency on `future`

backend/copr_backend/createrepo.py
To debug cases like #2315 in the future (if they will happen again)
=> backend: log task dict returned from redis to better debugging

.packit.yaml
e.g. in #2804 python-copr-common has to be built before FE so FE build can pass
=> packit: wait for python-copr-common to build first

backend/copr-backend.spec, backend/tests/conftest.py, backend/tests/testlib/__init__.py
https://github.com/fedora-copr/test-data-copr-backend/pull/1
=> backend: update tests to work with new test-data tarball

dist-git/tests/test_importer.py
The 'has_calls" actually never worked - it was a typo which had a no-op effect - and with the Python 3.12 in Fedora 39+ it finally started failing.
Let's switch to a valid 'assert_has_calls' and update the expected output (which is a bit artificial after the years, but it doesn't matter).
Relates: #2811
=> dist-git: fix test_do_import test

cli/copr_cli/main.py, frontend/coprs_frontend/coprs/forms.py
The 'description' metadata for 'short-input-field' is not visible anyway, so it was useful.  The priority field is nicely documented in 'dnf.conf' manual page, so it is fair to delegate our users there.
=> cli, frontend: rely on DNF with documenting repo priority

frontend/coprs_frontend/alembic/versions/08dd42f4c304_connect_copr_to_actions.py, frontend/coprs_frontend/commands/rawhide_to_release.py, frontend/coprs_frontend/coprs/logic/actions_logic.py, frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/coprs/models.py
This will help to implement RFEs like #1108
TODO:
~~Merge after #2733 and change `down_revision` to `7d9f6f921fa0`~~ done
Closes #2823
=> frontend: add relationship between actions and projects/builds

backend/copr-backend.spec, backend/copr_backend/background_worker_build.py, backend/copr_backend/helpers.py, backend/tests/test_background_worker_build.py, backend/tests/testlib/__init__.py, beaker-tests/Sanity/copr-cli-basic-operations/runtest-build-results-json.sh, rpmbuild/copr-rpmbuild.spec, rpmbuild/copr_rpmbuild/automation/srpm_results.py, rpmbuild/copr_rpmbuild/helpers.py
=> Move package NEVR parsing to builder

frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py, frontend/coprs_frontend/tests/coprs_test_case.py, frontend/coprs_frontend/tests/test_views/test_backend_ns/test_backend_general.py
=> Wait for delete actions before forking

frontend/coprs_frontend/alembic/script.py.mako, frontend/coprs_frontend/alembic/versions/c6dd61c09256_buildchroot_tags.py, frontend/coprs_frontend/config/copr.conf, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_builds.py, frontend/coprs_frontend/tests/coprs_test_case.py, frontend/coprs_frontend/tests/request_test_api.py, frontend/coprs_frontend/tests/test_resubmit.py
This feature is to get "high performance" builders into Copr: https://github.com/fedora-copr/debate/blob/main/2023-07-28-high-performance-builders.md https://github.com/praiskup/resalloc/pull/118
=> frontend: allow config-based build-chroot tags

backend/copr-backend.spec, backend/tests/test_modifyrepo.py, backend/tests/testlib/repodata.py
Fix #2832
Since F39 we are using zst compression for repodata instead of gz. https://fedoraproject.org/wiki/Changes/createrepo_c_1.0.0
=> backend: fix tests for zst compression on F39+

rpmbuild/copr_rpmbuild/automation/fedora_review.py
See https://pagure.io/FedoraReview/pull-request/463 
See https://pagure.io/FedoraReview/issue/310
I am planning to use this file from the fedora-review-service and provide users with better feedback based on that.
Also, we don't need to depend on a specific fedora-review version. If the file is not present, we skip it without failing.
=> rpmbuild: save review.json from fedora-review

backend/run/copr-backend-unknown-resalloc-tickets.py
- better explanation
- typo printing "This seems like a new ID: %d 9734"
- executable bit
=> backend: unknown-resalloc-tickets fixes

rpmbuild/copr_rpmbuild/automation/rpm_results.py, rpmbuild/copr_rpmbuild/automation/srpm_results.py
Fix #2841
The previous check worked for all SRPM methods except for custom method. It uses `self.chroot` to specify "what chroot to run the script in". Checking `source_type` should be more reliable.
=> rpmbuild: more reliable SRPM vs RPM build check

backend/copr_backend/background_worker_build.py, frontend/coprs_frontend/coprs/logic/builds_logic.py
Use "log.exception()" which passes the traceback down to backend.log. This helps me to debug some release-blocker issue right now, normally we (when infra is OK) we shouldn't ever catch an exception there.
=> backend: don't eat the "build detail collecting" traceback

rpmbuild/copr-rpmbuild.spec, rpmbuild/mock-custom-build.cfg.j2
We don't have to install 'dnf builddep' into bootstrap at all, we can go straight to the 'buildroot' installation.
=> rpmbuild: speedup the custom build with mock bootstrap image

frontend/coprs_frontend/coprs/auth.py, frontend/coprs_frontend/coprs/context_processors.py, frontend/coprs_frontend/coprs/oidc.py, frontend/coprs_frontend/tests/test_auth.py
As our former OIDC PR #2422 didn't have ability to grab any group info from Idp,
This PR add the missing functionalities:
1. unitfied the update group API, so it can be use by LDAP, openID and OIDC
2. suppose our OIDC Idp can return sort of group info like
```
{
"sub": "user123",
"name": "John Doe",
"email": "john.doe@example.com",
"groups": [
"dev-utils",
"eBPF",
"kernel"
]
}
```
PS: to achieve this, our Idp implement a non-standard but defacto standard: `group` scope and we add it in the `OIDC_SCOPES` config item
3. some refactor for oidc module: make `oidc_enabled` more useful, which will guarantee the OIDC related configs is configured and valid
try to fix: #2788
=> frontend: support grab group info from OIDC provider

rpmbuild/copr-rpmbuild.spec
=> rpmbuild: require new python-specfile version

.packit.yaml
We have changed the behaviour of getting latest tags from the repository in Packit (https://github.com/packit/packit/pull/2030/)
and therefore, for repositories with multiple versioning schemas, it is necessary to add these options.
These changes will land in production tomorrow morning, that would be the ideal time to merge this PR. Sorry for the inconvenience!
For more details, see https://packit.dev/docs/configuration#upstream_tag_include
=> Add upstream_tag_include to Packit config

backend/copr-backend.spec, backend/copr_backend/background_worker_build.py, backend/tests/test_background_worker_build.py
Fix #2850
CI for this will probably fail. We need merge tests data PR
https://github.com/fedora-copr/test-data-copr-backend/pull/2
and tag a new version first.
=> Parse specfile or RPM headers only once

frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/tests/test_apiv3/test_build_chroots.py
This is what we prefer doing in FE<->BE protocol, what we return in result.json in BE<->Builder protocol, and what we _should_ return to users.
=> frontend: allow "epoch is null" field in BuildChrootResult

beaker-tests/Sanity/copr-cli-basic-operations/helpers, beaker-tests/Sanity/copr-cli-basic-operations/runtest-bootstrap.sh, beaker-tests/Sanity/copr-cli-basic-operations/runtest-build-results-json.sh, beaker-tests/Sanity/copr-cli-basic-operations/runtest-exclusivearch.sh, beaker-tests/Sanity/copr-cli-basic-operations/runtest.sh
Mock 5.0 is enforced by the new Copr release, and there's the bootstrap_image feature that can not use "fedora image" for EPEL target chroot
The unspecified `Epoch` tag in spec file is newly evaluated as "null" value in the BuildChrootResults table, and returned as None to end-user (null JSON value).
The default PyPI method is pyp2spec, not pyp2rpm now.  Let's use a package that is easily buildable with pyp2spec (motionpaint doesn't comply with the new licensing format, we could submit PR but that would require a release into PyPI, and ...).
Skip one test related to a ExclusiveArch parsing for now; our ppc64le builders are somewhat broken or non-standard, see #2870.
Several cleanup actions are now wrapped with cleanupAction, so we can keep the intermediate files/projects hanging around …
=> beaker: align tests with the August 2023 release

backend/copr_backend/background_worker_build.py, backend/copr_backend/sshcmd.py, backend/tests/testlib/__init__.py
All the SSHConnection "public" methods now have subprocess_timeout option.  If the option is set, and the local utility (ssh or rsync) doesn't finish within the specified timeout, SSHConnectionError is raised as in any other connection-issues situation.
The SSHConnection.run() and SSHConnection.run_expensive() methods have the default timeout set to 180s by default.  The reason is that both of those commands are always expected to finish reasonably quick (much less than 10s).  If not, after 180s period we can either expect the builder is dead, or optionally retry.
The timeout detection should help us to cover weird situations like in the issue #2888.  If the remote process is in 'D' state (uninterruptible sleep), we simply kill the ssh client (subprocess) locally.  Subsequent …
=> backend: react on staled SSH connections

rpmbuild/copr_rpmbuild/automation/__init__.py, rpmbuild/copr_rpmbuild/automation/base.py, rpmbuild/copr_rpmbuild/automation/srpm_results.py, rpmbuild/copr_rpmbuild/helpers.py, rpmbuild/main.py
Fix #2881
The Copr macros are documented here
https://docs.pagure.org/copr.copr/user_documentation.html#rpm-macros
=> rpmbuild: use Copr custom macros when parsing the specfile

frontend/coprs_frontend/coprs/templates/_helpers.html, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
This is taking so much time. And even when it is cached it is taking down whole server.
=> frontend: do not display recent builds box on main page

frontend/coprs_frontend/coprs/__init__.py, frontend/coprs_frontend/coprs/oidc.py
The `oidc.py` has logging statements in case some configuration
options are missing. They traceback with this weird traceback because
they don't use our configured logger from `app`.
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
return self._format(record)
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
return self._fmt % values
~~~~~~~~~~^~~~~~~~
KeyError: 'user'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
...
=> Fix tracebacks from OIDC

common/python-copr-common.spec
~~This means that python-copr-common is no longer compatible with Python 2 and EPEL 7, but we stay compatible with Python 3.6 on EL8+.~~
~~If we ever want make it compatible with EL7, we should even there use the Python 3 (python36) stack.~~
Just adding python-six into BuildRequires.
=> Explicitly depend on python3-six

backend/copr_backend/background_worker_build.py, backend/copr_backend/job.py, rpmbuild/copr_rpmbuild/automation/fedora_review.py, rpmbuild/copr_rpmbuild/helpers.py
This is really hacky and unpleasant. `fedora-review` does not have a way to set a custom log path, and adding one will not be easy. You have to wait for it to have parsed the command line arguments, and by that point it's already expecting to have started logging. See <https://pagure.io/FedoraReview/blob/master/f/src/FedoraReview/settings.py#_44> and its uses for more context.
This PR redirects everything that's looking at `$XDG_CACHE_HOME` into a unique directory per run, then discards everything except the `fedora-review` logs in that directory. I am very open to suggestions of better ways to do this. 
For all its many many faults though, this did work when I tested it locally.
Resolves #2919
=> Collect Fedora Review Logs After Runs

backend/conf/copr-be.conf.example, backend/copr-backend.spec, backend/copr_backend/daemons/build_dispatcher.py, backend/copr_backend/helpers.py, backend/copr_backend/rpm_builds.py, backend/tests/test_config_reader.py, backend/tests/test_worker_limits.py, common/copr_common/worker_manager.py, common/python-copr-common.spec, common/setup.py, dist-git/copr-dist-git.spec, dist-git/copr_dist_git/import_dispatcher.py
The default "max_workers" limit might be too large (e.g. in Fedora Copr it is 45) compared to the number of available workers of some architecture type (e.g. for s390x there's now max 18 workers, and ppc64le is often limited too due to #2869).  This patch then brings another FUP mitigation.
=> backend: provide per-arch & per-owner worker limit

frontend/coprs_frontend/config/copr.conf, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
This is still useful for the Red Hat Internal Copr instance.
=> frontend: show recent copr builds on homepage as opt-in

backend/copr_backend/sign.py
Fix #2911
Fix #2942
When frontend is creating a new project, it creates an action to generate GPG keys. This may fail because of a temporary keygen downtime or network issues.
Once a SRPM is built, we try to use the GPG key and it doesn't exist, there is a fallback, trying to generate the key again. We can try longer.
To trigger this fallback, you can do:
docker-compose stop keygen-httpd
copr create test-srpm-key --chroot fedora-38-x86_64
copr buildscm --clone-url ... test-srpm-key
docker-compose start keygen-httpd
=> Improve the fallback for generating GPG keys

doc/user_documentation.rst
Taken from Diego Herrera from Fedora devel list
=> doc: faq - how to handle autospec

doc/user_documentation.rst
Point users at the https://rpm-packaging-guide.github.io/ instead of the dying rpkg-util, and experiment with English corrections by AI.
=> doc: cleanup the Quick Start part

backend/copr_backend/background_worker_build.py, backend/copr_backend/sign.py
In the commit d87321b4d6deb22211521db099760fb2fa560311 we skipped the "signing" job itself, but the problem also happens for downloading pubkey from copr-keygen.
Complements: d87321b4d6deb22211521db099760fb2fa560311
Fixes: #2942
=> backend: worker to not call keygen for source builds

backend/run/copr-backend-unknown-resalloc-tickets.py
We always printed the "header-like" message, and the output was a bit unreadable.
=> backend: nicer unknown-resalloc-tickets output

backend/copr_backend/vm_alloc.py, backend/tests/test_vm_alloc.py
If the `cmd_new` (pools.yaml config) commands returns a YAML-formatted output, try to parse 'host' and 'name' fields.  The 'name' in particular should match the RESALLOC_NAME.
=> backend: self-identify the resalloc resource in logs

CONTRIBUTE.md, frontend/coprs_frontend/coprs/logic/complex_logic.py, frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/coprs/views/apiv3_ns/__init__.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_build_chroots.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_project_chroots.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_builds.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_chroots.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py, frontend/coprs_frontend/coprs/views/groups_ns/groups_general.py, frontend/coprs_frontend/coprs/views/misc.py, frontend/coprs_frontend/coprs/views/user_ns/user_general.py, frontend/coprs_frontend/coprs/views/webhooks_ns/webhooks_general.py, frontend/coprs_frontend/pagure_events.py, frontend/coprs_frontend/tests/test_logic/test_complex_logic.py
Originally, safe methods were considered as methods raising ObjectNotFound for API (mainly with session.one() method). Now methods which returns None or ignores the error completely are also considered as "safe".
For the sake of consistency:
- *_or_none -> returns None if object was not found in the database
- *_safe -> methods that ignores error completely (they basically logs and/or are safe from exceptions)
and renaming some of the current safe methods to normal ones that aren't safe by the new rules
=> frontend: unify naming convention for safe methods

frontend/coprs_frontend/alembic/env.py, frontend/coprs_frontend/alembic/versions/4d06318043d3_add_buildchroot_id_and_coprchroot_id.py, frontend/coprs_frontend/alembic/versions/65a172e3f102_unquote_counter_stat_urls.py
All the migrations need to have correct path set, if something from copr_frontend needs to be loaded.
The `env.py` Base needs to be loaded differently with the new Flask-SQLAlchemy version on F39.
=> frontend: make alembic working on F39+

frontend/coprs_frontend/coprs/models.py
=> frontend: Add backref relationship between Package and Build to silence sqlalchemy warnings

doc/index.rst, frontend/coprs_frontend/coprs/templates/contact_us.html, python/docs/index.rst
This is because of the IRC <-> Matrix bridge isn't working: https://communityblog.fedoraproject.org/matrix-to-libera-chat-irc-bridge-unavailable/
And it seems that Fedora teams are advised to move (certainly Fedora Infra team, corresponding meetings, etc. is):
https://pagure.io/fedora-infrastructure/issue/11460
Resolves: #3006
Complements: #3047
=> Copr community is moving from IRC to Matrix

keygen/src/copr_keygen/logic.py, keygen/tests/test_logic.py
This seems to be much faster than `--list-secret-keys` on our production instance.
=> keygen: try to export a key to find whether it exists

cli/copr_cli/main.py
=> Fix typo in --namespace help output

frontend/coprs_frontend/config/copr.conf, frontend/coprs_frontend/coprs/auth.py, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/oidc.py, frontend/coprs_frontend/coprs/views/misc.py
The current OpenID Connect code assumes the existence of a non-standard field in the UserInfo returned by the provider, limiting the ability to use non-Ipsilon OIDC providers; however, the standard forbids using corresponding standardised field (preferred_username) as a unique user identifier, a property on which Copr relies.
This commit adds a fall back path to the OIDC code that will use preferred_username anyway if the administrator asserts that the values will be unique in practice with a new configuration option.  The upshot of this change is that administrators can now use OIDC providers like Gitea/Forgejo.
Fixes #3008.
=> frontend/oidc: add OIDC_UNIQUE_PREFERRED_USERNAMES

frontend/coprs_frontend/coprs/logic/complex_logic.py
The query comes from users and does not need to conform the regexp that we uses when creating a project. In fact the string may contain unicode characters that cannot be converted to ascii stream.
Fixes: #3072
Addressing:
```
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 244, in wrapper
copr = ComplexLogic.get_copr(username, coprname, with_mock_chroots=True) …
```
=> convert eror message to binary text before emitting

frontend/coprs_frontend/coprs/logic/coprs_logic.py
We create new CoprDir but then call send_createrepo() and if somebody in meantime create CoprDir we got sqlalchemy.exc.IntegrityError and the end of send_createrepo when SQLAlchemy flushes.
Fixes: #3058
=> fix race condition when creating CoprDir

frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
Previously the render_generate_repo_file was memoized() so subsequent downloads was not counted. Now the function is not memoized() and CounterStatLogic.incr() is always called and only rest of the function is memoized().
=> count every download of repo file

frontend/coprs_frontend/coprs/forms.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/fields.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py, frontend/coprs_frontend/tests/test_apiv3/test_projects.py, python/copr/v3/proxies/project.py
=> frontend, python: allow ignoring errors that a project already exists

frontend/coprs_frontend/coprs/logic/stat_logic.py
Previously we claimed that this method does commit. But it did just add() - and that does not commit. We do a commit now. And during a commit we check for integrity error. If that happens that means somebody inserted it just second ago. So lets try read again.
Fixes: #3073
=> fix race condition when creating new record for repo stat counter

rpmbuild/main.py
As of 302a78f, `MockBuilder.prepare_configs()` does not take a `configdir` argument, nor does it return a list of written config files.
=> Fix copr-rpmbuild --dump-configs

build_aux/Containerfile.unittest, docker/backend/Dockerfile, docker/builder/Dockerfile, docker/distgit/Dockerfile, docker/frontend/Dockerfile, docker/keygen/Dockerfile, docker/resalloc/Dockerfile
We have centos7 images for postgres and nginx which are fairly old images - should we e.g. build our own in quay with rocky linux 9?
Fixes #2945
=> docker: increment fedora images to 39

backend/conf/logrotate/copr-backend, dist-git/conf/logrotate, frontend/conf/logrotate, keygen/configs/logrotate
The log files consume a lot of storage (7G Fedora Copr backend).  We probably never analyzed older logs than 6 weeks, so lets shorten the "keep" period.
Fixes: #2944
=> backend, dist-git, frontend, keygen: keep logs 6 weeks instead of 13

messaging/copr_messaging/private/hierarchy.py, messaging/copr_messaging/private/schema_old.py, messaging/copr_messaging/private/schema_stomp_old.py, messaging/copr_messaging/schema.py, messaging/copr_messaging/tests/test_schema.py
This sets a few properties that are standard in Fedora Messaging schemas and will allow notifications to be emitted by FMN.
=> Messaging: Set the agent_name, usernames and groups properties

backend/copr_backend/background_worker_build.py, backend/copr_backend/daemons/build_dispatcher.py, backend/copr_backend/helpers.py, backend/copr_backend/job.py, backend/copr_backend/rpm_builds.py, backend/copr_backend/sshcmd.py, backend/tests/test_config_reader.py, backend/tests/testlib/__init__.py, common/copr_common/helpers.py, common/python-copr-common.spec, common/setup.py, frontend/coprs_frontend/alembic/versions/41763f7a5185_add_ssh_public_keys_column.py, frontend/coprs_frontend/coprs/forms.py, frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/coprs/templates/coprs/detail/_builds_forms.html, frontend/coprs_frontend/coprs/templates/coprs/detail/add_build/rebuild.html, frontend/coprs_frontend/coprs/templates/coprs/detail/build.html, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_builds.py, frontend/coprs_frontend/tests/test_views/test_backend_ns/test_backend_general.py, rpmbuild/bin/copr-builder, rpmbuild/copr-rpmbuild.spec
Implementation of https://github.com/fedora-copr/debate/pull/6
Fixes: #2364
=> Rebuild and allow user SSH

common/copr_common/request.py
When copr retrieves an SRPM from a URL it uses a `User-Agent` string of the form `python-requests/2.28.2`, being the default provided by the Python 'requests' library.
Unfortunately my shared hosting provider has started rejecting requests using this user agent string because it is associated with bots performing a de facto DOS attack on the server.
Arguably this frustrating balancing act for the web server host is not copr's fault. However, it feels like providing a more application-specific user agent string would, apart from working around this problem, be a good idea in its own right and give web hosts an accurate indication of the nature of the automated requests they receive.
This patch provides a user agent string of the form `copr-common/<version>` and works around the problem …
=> common: use 'copr-common/<version>' as http user agent

cli/copr_cli/main.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py
Copr build <projectname:dirname> should according to documentation create the dirname if does not exists, but the early check check_before_build in action_build actually runs /build/check-before-build endpoint even before the <projectname:dirname> has a chance to be created, thus complains about non-existent dirname.
Passing only projectname to the check should be enough for the check as is since the /build/check-before-build is called once more after dirname creation.
Fixes #2786
=> cli: dont check dirname presence in action_build

beaker-tests/Sanity/copr-cli-basic-operations/runtest-openmandriva.sh, doc/how_to_upgrade_builders.rst
=> Update documentation while upgrading builders to F39

frontend/coprs_frontend/coprs/helpers.py, frontend/coprs_frontend/coprs/views/apiv3_ns/__init__.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_mock_chroots.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_modules.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_monitor.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_webhooks.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/fields.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py
=> frontend: migrate monitor, modules, mock_chroots, webhooks enpoints to restx

rpmbuild/mock-custom-build.cfg.j2, rpmbuild/mock.cfg.j2
The Jinja statements are only expanded in the values of the config_opts dictionary, not in the keys. The new mock-core-configs version 40.2 contains a Jinja condition in the package_manager value. Therefore, we cannot simply use it as a key in config_opts.
Since yum.conf and dnf.conf are aliases (starting from Mock 2.1), and dnf5.conf (starting from Mock 5.0+), we can avoid using the variable as a key entirely.
Relates: https://github.com/rpm-software-management/mock/commit/5d620ad326d
Relates: https://github.com/rpm-software-management/mock/pull/1332
Fixes: #3146
=> rpmbuild: no Jinja-vars in config_opts keys

rpmbuild/mock-custom-build.cfg.j2
=> rpmbuild: don't set bootstrap_image_ready for rawhide

doc/user_documentation.rst
Fix #3104
We skipping such projects with the following explanation.
Exploring projectdir 'kde6' with path: /var/lib/copr/public_html/results/solopasha/kde6
Going to prune solopasha/kde6
projectname = kde6
Skipped solopasha/kde6 since auto createrepo option is disabled
So I am just documenting the status quo.
=> doc: exempt projects with manual createrepo from pruning old results

doc/user_documentation.rst, doc/video_tutorial.rst
My Saturday hike got canceled and I got the whole weekend for myself, so I started working on one of the things that used to be in my _compass_ for a long time - a series of short videos about Copr.
I listed them on a documentation page so they can be easily linked together and teased what topics will get covered in the future.
What do you think?
At this moment, the videos are marked on youtube as "unlisted" and haven't shared them anywhere yet in case you had some critical feedback. Also, they don't have pretty thumbnails yet.
=> doc: add video tutorial page

cli/copr_cli/main.py
Several places that intend to use self.username did not actually assign the return value. This fixes `copr list` without  username argument.
=> Actually assign fallback value from self.username

common/copr_common/background_worker.py
... for compatibility with python 3.6.
=> common: add `contextlib.nullcontext` function

common/copr_common/background_worker.py
E.g. resalloc agent spawner now uses this library, and corresponding deployments there's no 'copr' user.
=> common: fix misleading warning for non-copr users

rpmbuild/bin/copr-builder
we have this help message as motd on builders (https://pagure.io/fedora-infra/ansible/pull-request/1797)
=> rpmbuild: drop copr-builder help message

backend/copr_backend/background_worker_build.py
Complements: 7afb039b2a7818723ce9c6ed10d27bd922a1b3d8
=> backend: use correct (renamed) _discard_running_worker

frontend/coprs_frontend/run/check_for_anitya_version_updates.py
Fix #3056
We are seeing the following error in the logs:
RuntimeError: Working outside of application context.
This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
=> frontend: run the check for anitya updates script under app context

backend/copr_backend/background_worker_build.py
=> backend: print user SSH instructions before the build starts

rpmbuild/copr_rpmbuild/builders/mock.py
=> rpmbuild: don't clean after builds with user ssh access

common/copr_common/redis_helpers.py
The check like:
if hasattr(opts, "redis_port"):
kwargs["port"] = opts.redis_port
Can not work with dict() objects.  The hasattr() actually doesn't work this way.
See: https://github.com/praiskup/resalloc/pull/154
=> common: make get_redis_connection to accept dict(opts)

frontend/coprs_frontend/commands/clean_expired_projects.py, frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/logic/complex_logic.py, frontend/coprs_frontend/tests/test_logic/test_builds_logic.py
Fix #2489
I tried this on today's database dump and it took 46m24.731s to finish and my laptop was fine. I think the crash was prevented by not committing everything at once.
=> frontend: speedup the removal of temporary projects

common/copr_common/helpers.py
For non-special-cases, we want to use the `name-` part from chroot name as the abbreviation.  Fixes traceback:
$ ./manage.py create_chroot epel-7-i386
INFO:__main__:Running command: ./manage.py create_chroot epel-7-i386 Traceback (most recent call last):
File "/copr/coprs_frontend/./manage.py", line 143, in <module>
app.cli()
File "/usr/lib/python3.12/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
=> common: fix chroot_to_branch default

backend/tests/test_helpers.py, backend/tests/test_modifyrepo.py, backend/tests/test_sign.py, rpmbuild/tests/test_distgit_client.py
Fix #3197
Fix RHBZ 2272042
Fix RHBZ 2272044
There is no reason for those methods to be static. Seems mostly like a typo.
=> backend, rpmbuild: remove static methods from tests

beaker-tests/Sanity/copr-cli-basic-operations/bz1457888.sh, beaker-tests/Sanity/copr-cli-basic-operations/helpers, beaker-tests/Sanity/copr-cli-basic-operations/runtest-exclusivearch.sh, beaker-tests/Sanity/copr-cli-basic-operations/runtest-makesrpm-fail.sh, beaker-tests/Sanity/copr-cli-basic-operations/runtest.sh
There was some temporary networking issue when I was running beaker tests. The issue seems to have resolved itself within an hour but I migrated all our test repositories to GitHub anyway.
Please note that I changed some of the repository names so that they all have a `copr-test-` prefix.
=> beaker-tests-sanity: migrate test repositories from Pagure to GitHub

frontend/coprs_frontend/coprs/templates/coprs/detail/_builds_forms.html
=> frontend: fix bug in reporting failed SRPMs to log-detective

cli/copr-cli.spec, cli/copr_cli/util.py, cli/setup.py
Fix #2539
The output of `json.dumps` and `simplejson.dumps` is equivalent for listing builds and listing packages. I am removing the `for_json` parameter because there is not equivalent. However it shouldn't make any difference because:
> If for_json is true (not the default), objects with a for_json()
> method will use the return value of that method for encoding as JSON
> instead of the object.
We don't define any `for_json` methods for our objects.
=> cli: remove dependency on simplejson

python/copr/v3/requests.py
=> python: suggest pagination only when a GET request timeouts

frontend/coprs_frontend/coprs/views/apiv3_ns/__init__.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_build_chroots.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_general.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_modules.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_packages.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_permissions.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_project_chroots.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_webhooks.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/fields.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py, frontend/coprs_frontend/coprs/views/misc.py
review this after #3168
Fixes #2809, fixes #2997
#2809 has some optional issues but the main migration is done so I think we can close the epic and keep those optional as individuals
=> Finish flask restx migration

beaker-tests/Sanity/copr-cli-basic-operations/runtest-build-batches.sh
Otherwise we are running watch-build on the same build three times:
copr watch-build 2918252 2918252 2918252
=> beaker-tests-sanity: add -s so we can parse the build ID

frontend/coprs_frontend/commands/update_indexes.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py, frontend/coprs_frontend/coprs/views/groups_ns/groups_general.py
=> Hide temporary projects

frontend/coprs_frontend/coprs/mail.py, frontend/coprs_frontend/tests/test_mail.py
The list of chroots in the e-mail is now sorted deterministically; we report the soonest expiring first, then we sort alphabetically.
The testsuite is more deterministic too, `chroot[3]` was pointing to an unexpected chroot on my box.
=> frontend: eol-emails deterministic

frontend/coprs_frontend/alembic/versions/65a172e3f102_unquote_counter_stat_urls.py
The SyntaxWarning appeared in every `alembic up/down..` call.
In [1]: print("%\%40%")
<>:1: SyntaxWarning: invalid escape sequence '\%'
<ipython-input-1-b80c71bbab44>:1: SyntaxWarning: invalid escape sequence '\%'
print("%\%40%")
%\%40%
In [2]: print("%\\%40%")
%\%40%
=> alembic: fix a migration syntax warning

doc/user_documentation.rst
The page of high_performance_builders is referenced only from FAQ. I have hard time finding it. Lets put it in main document and notably to the left menu where it is discoverable.
=> doc: add high_performance_builders to user documentation menu

README.md
GitHub has this super useful feature where you can click that icon in the top right of a markdown code element to copy the text, and it kind of annoys me when i can't simply copy&paste the text to the terminal.
=> Remove the dollar signs in the command in the readme

rpmbuild/copr-rpmbuild.spec
Traceback (most recent call last):
File "/usr/bin/copr-distgit-client", line 7, in <module>
from copr_distgit_client import main
File "/usr/lib/python3.12/site-packages/copr_distgit_client.py", line 14, in <module>
from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'
=> rpmbuild: copr-distgit-client depends on python-six

doc/how_to_manage_chroots.rst
For the third time, I forgot to disable EOL chroots from the Fedora Review Service before they were disabled from Copr, causing an unexpected outage.
Until it starts using
https://github.com/rpm-software-management/fedora-distro-aliases this documentation change should prevent any further instances of this issue.
=> doc: check that our services don't use the going-to-be-deactivated chroot

backend/copr_backend/helpers.py, backend/run/copr-backend-analyze-results, backend/run/copr-repo
Addressing:
/usr/bin/copr-backend-analyze-results:153: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
timestamp = datetime.utcnow().isoformat()
=> utcnow() is deprecated

doc/conf.py, doc/developer_documentation.rst, doc/developer_documentation/eol-logic.rst, doc/how_to_manage_chroots.rst, frontend/conf/cron.daily/copr-frontend-optional, frontend/coprs_frontend/alembic/versions/d23f84f87130_eol_rolling_builds.py, frontend/coprs_frontend/commands/alter_chroot.py, frontend/coprs_frontend/commands/eol_lifeless_rolling_chroots.py, frontend/coprs_frontend/config/copr.conf, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/helpers.py, frontend/coprs_frontend/coprs/logic/actions_logic.py, frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/logic/complex_logic.py, frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/coprs/logic/outdated_chroots_logic.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/manage.py, frontend/coprs_frontend/tests/coprs_test_case.py, frontend/coprs_frontend/tests/test_logic/test_coprs_logic.py, frontend/coprs_frontend/tests/test_logic/test_outdated_chroots_logic.py
Implements: https://github.com/fedora-copr/debate/blob/main/2024-04-23-rawhide-chroots-eol.md
Fixes: #2933
=>     frontend: automatically EOL lifeless rolling chroots

backend/copr_backend/actions.py, backend/copr_backend/pulp.py, backend/copr_backend/storage.py, frontend/coprs_frontend/coprs/logic/actions_logic.py
=> Implement chroot deletion in Pulp

backend/copr_backend/pulp.py, backend/tests/test_pulp.py
The pulp.stage.devshift.net instance has domains enabled while our STG instance has them disabled. As long as it is easy to support both cases, I'd do that.
=> backend: add support for pulp domains

backend/copr_backend/actions.py, backend/copr_backend/background_worker_build.py, backend/copr_backend/pulp.py, backend/copr_backend/storage.py
There is one small exception and that is `publish_repository` which takes `**kwargs` for parameters that differ across storages.
=> backend: remove fake jobs and pass specific arguments to storage calls

frontend/coprs_frontend/coprs/forms.py
Should fix https://github.com/packit/packit-service/issues/2446
=> frontend: align delete_after_days validators

docker-compose.yaml
It is annoying when doing for example
docker-compose \
-f docker-compose.yaml \
-f docker-compose.shell.yaml \
up -d backend-build
Then it re-creates also `backend-log`.
=> docker: don't depend other backend containers on log container

frontend/coprs_frontend/coprs/helpers.py, frontend/coprs_frontend/tests/test_helpers.py
Fixes https://github.com/fedora-copr/copr/issues/3334.
=> frontend: use the same repofile for all CentOS Stream versions

backend/copr_backend/pulp.py
six module is not required and cannot be installed. And we are python3 only anyway. So remove it.
=> backend: do not use six

keygen/copr-keygen.spec, keygen/requirements.txt, keygen/setup.py, keygen/tests/test_handles.py, keygen/tests/test_logic.py
=> keygen: drop support for python2

frontend/coprs_frontend/coprs/views/apiv3_ns/schema/fields.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py
An attempt number 356 to remove magic and excess complexity from our APIv3 schemas. I won't sleep soundly until we figure it out, so in order to preserve my own sanity, here we go.
- I am keeping schemas as `@dataclass`, we already figured out that it is what we want
- I am keeping shared fields in `fields.py` but moving only once used fields definitions directly to schemas
- I am removing some magic:
- It is no longer possible to mark all fields as required. The largest schema that did it had 3 fields.
- We are no longer magically matching schema fields by their name with their definitions in `fields.py`
- Because of this ^^, we don't need the hack for renaming field names
- I simplified a lot of code in `Schema`, `InputSchema`, and `ParamsSchema`
When reviewing, I recommend going commit …
=> Yet another attempt to remove APIv3 magic

frontend/coprs_frontend/alembic/versions/06b208e317a3_create_webhook_history_table.py, frontend/coprs_frontend/coprs/helpers.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/coprs/views/webhooks_ns/webhooks_general.py, frontend/coprs_frontend/tests/test_webhooks.py
This is a two part PR. 
1. To implement the database side of things(models, migrations and data insertion up webhook arrival).
2. To implement the UI which is to display the webhook history records in one of a chosen Project page.
Here's what I've done so far, 
1. Add a new table named `webhook_history` to `coprdb` DB. 
- It has three Columns. 
- `id` : An auto incrementing primary key.
- `hook_uuid` : This is extracted from the webhook POST request. 
- `build_id` : Build number that was initiated by a webhook. 
- Note: A webhook may initiate multiple builds this implies there may be multiple records inserted with the same `hook_id`. 
2. A function named `def addHookHistoryRecord(hook_uuid, builds_initiated_via_hook)` is used to insert a record in `webhook_history` table. As of now, I am …
=> Webhook request history

dist-git/copr-dist-git.spec, dist-git/copr_dist_git/package_import.py, dist-git/tests/generate_quick_package, dist-git/tests/test_crazy_merging.py
Fix #3365
The rpkg-1.67-1 first introduced this check which was implemented in
https://pagure.io/rpkg/pull-request/700
At first I thought the check is valid and we only have incorrectly named spec files and repositories in our tests. But rpkg-1.67-1 actually breaks importing even for our real usage. This leads me to think that when they compare the spec and repo name, they forget to strip a namespace from the repo name.
=> Don't check that specfile matches the repository name

backend/copr_backend/background_worker_build.py, backend/tests/test_background_worker_build.py
Fix #3343
I am not 100% sure this PR will fully prevent issues like #3343 but I am trying to address cases like this here.
Normally, copr-rpmbuild is responsible for terminating itself when the build timeout is reached. This is indicated by the "Copr timeout => sending INT" message in the builder-live.log.
This proves itself to not be reliable enough because sometimes the whole copr-rpmbuild process hangs up, doesn't terminate itself, and the build gets stuck in the running state for months. This PR implements a fail-safe mechanism on backend, which waits a short period of time after the timeout is reached and then terminates the build.
Backend terminates the timeouted builds by connecting to the broken builders and running `copr-rpmbuild-cancel` on them. This successfully terminated the …
=> backend: implement timeout fail-safe in case copr-rpmbuild hangs up

backend/copr-backend.spec, backend/run/copr-repo, backend/tests/test_modifyrepo.py, common/copr_common/lock.py, common/python-copr-common.spec, common/setup.py, dist-git/copr-dist-git.spec, dist-git/copr_dist_git/helpers.py, dist-git/copr_dist_git/importer.py, dist-git/tests/test_importer.py
Fix #3367
As a consequence, stop using `python3-oslo-concurrency` on Copr DistGit and start using `python3-filelock` as the rest of the stack.
=> Unify file locking code in copr-common

backend/tests/daemons/test_log.py, backend/tests/daemons/unused_test_job_grab.py, backend/tests/run/test_copr_prune_results.py, backend/tests/test_frontend.py, cli/tests/cli_tests_lib.py, cli/tests/test_distgit.py, cli/tests/test_mock_config.py, dist-git/tests/test_crazy_merging.py, dist-git/tests/test_importer.py, dist-git/tests/test_package_import.py, rpmbuild/tests/test_mock.py
Fix #3351
The deprecation warning even says "Use @pytest.fixture instead; they are the same".
=> Use fixture instead of deprecated yield_fixture

docker-compose.yaml, docker/resalloc/Dockerfile, docker/resalloc/files/etc/resallocserver/server.yaml
Available at http://127.0.0.1:5005/
When running the `resalloc-webui` container for the first time, it will probably be necessary to manually rebuild the `resalloc` container first, to create the database on a shared volume.
docker-compose up -d --build resalloc
=> Add resalloc-webui container

backend/copr_backend/pulp.py, backend/copr_backend/storage.py
Fix https://github.com/pulp/pulp_rpm/issues/3719
Instead of uploading RPM packages as artifacts in one API call, and then creating a content from them in a separate call, we will now create the content directly.
There are mutiple reasons to do so:
- One API call instead of two
- It fixes the issue with installing packages mentioned above
- @dkliban says there is an effort to not allow uploading artifacts on shared Pulp instances
There is only one disadvantage of doing this, we lose track of what RPM packages belong to a specific Copr build ID. We will use labels for this, once they are implemented.
See https://github.com/pulp/pulpcore/issues/3338#issuecomment-2255898417
=> Don't upload RPM packages to Pulp as artifacts

rpmbuild/copr-rpmbuild.spec, rpmbuild/tests/test_spec.py
introduced in commit 7dfb269ec0b898437640e32ac5e3f6d4f1d3297a
=> rpmbuild: cleanup el6 code

rpmbuild/copr-rpmbuild.spec
Addressing F41 installation issue:
Problém 9: problém s nainstalovaným balíčkem dnf5-5.2.5.0-20240829005832.58.gbe2e6bef.fc40.x86_64
- package dnf5-5.2.5.0-20240809005713.33.g98e6b01b.fc41.x86_64 from copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf5-unstable obsoletes yum < 5 provided by yum-4.21.1-1.fc41.noarch from fedora
- package dnf5-5.2.5.0-2.fc41.x86_64 from fedora obsoletes yum < 5 provided by yum-4.21.1-1.fc41.noarch from fedora
- package copr-builder-0.73-3.fc41.x86_64 from fedora requires dnf-yum, but none of the providers can be installed
- problém s nainstalovaným balíčkem copr-builder-0.73-1.fc40.x86_64
- yum-4.21.1-1.fc40.noarch from @System  does not belong to a distupgrade repository
- dnf5-5.2.5.0-20240829005832.58.gbe2e6bef.fc40.x86_64 from @System  does not …
=> rpmbuild: in F41 do not depend on yum

frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/templates/status/stats.html, frontend/coprs_frontend/coprs/views/status_ns/status_general.py
=> frontend: provide statistics on how many users submitted at least one build in past month

docker-compose.yaml, docker/backend/files/home/copr/.config/pulp/cli.toml
See #2533
We are using a multi-process container
https://pulpproject.org/pulp-oci-images/docs/admin/guides/deploy-multi-process-images/
=> Add pulp container to our docker-compose

backend/copr_backend/actions.py, backend/copr_backend/pulp.py, backend/copr_backend/storage.py, backend/tests/test_action.py, frontend/coprs_frontend/coprs/logic/actions_logic.py, frontend/coprs_frontend/tests/test_logic/test_builds_logic.py
=> backend, frontend: implement project and build deletion in Pulp

cli/copr_cli/main.py, cli/tests/test_cli.py, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/forms.py, frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py, frontend/coprs_frontend/tests/test_apiv3/test_projects.py, python/copr/v3/proxies/project.py
=> Configurable storage for new projects

docker-compose.yaml
Because of bug in python3-daemon [1] we need to set ulimits inside docker container, otherwise backend and dist-git ooms.
[1] - https://bugzilla.redhat.com/show_bug.cgi?id=2307635
Fix #3394
=> docker: set hard ulimits for docker container

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
This is TOCTOU issue.  The other checks for duplications (on so many places) seem kinda redundant because nothing but try/except for commit() may catch these concurrency problems.
Fixes: #3372
=> frontend: fix the 500 for racy creation attempts

messaging/copr_messaging/private/hierarchy.py, messaging/copr_messaging/schema.py
This PR contains 2 changes:
- set the one-line description to be the summary instead of the `__str__` representation (which goes in the email body)
- set the chroot message severity to DEBUG, which will not generate a notification in FMN by default. Those are always paired with a build message, so it makes more sense to notify on that one.
Fixes: #3237
=> Message schemas: improve the notifications

rpmbuild/copr-rpmbuild.spec
=> rpmbuild: do not require qemu-user-static on rhel

backend/run/copr-backend-unknown-resalloc-tickets.py
If no tickets are taken (which often happens in the staging environment), this script encountered corner case issues.
=> backend: unknown resalloc tickets helper cleanup

rpmbuild/copr-rpmbuild.spec, rpmbuild/copr-rpmbuild.yml, rpmbuild/copr_rpmbuild/builders/mock.py, rpmbuild/copr_rpmbuild/config.py, rpmbuild/copr_rpmbuild/helpers.py, rpmbuild/copr_rpmbuild/providers/base.py, rpmbuild/copr_rpmbuild/providers/custom.py, rpmbuild/mock-custom-build.cfg.j2, rpmbuild/mock.cfg.j2, rpmbuild/tests/test_base.py, rpmbuild/tests/test_mock.py, rpmbuild/tests/test_pypi.py, rpmbuild/tests/test_rubygems.py, rpmbuild/tests/test_scm.py, rpmbuild/tests/test_spec.py
This allows us to specify tpm fs size to rpmbuild in order to be able to
automatically generate its size for performance builders.
before merge (please review):
Fixes #3268
=> rpmbuilds: dynamically specify tmp_fs size

frontend/coprs_frontend/coprs/logic/builds_logic.py
Running `runtest-custom-method.sh`, we are seeing this failure in backend.log:
Unexpected exception (in /usr/lib/python3.12/site-packages/copr_backend/background_worker_build.py:431)
The problematic line is
timestamp = self.job.started_on + self.job.timeout + 60 * 60
and the hidden exception is
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
The `self.job.timeout` is taken from the frontend task, if it is set. The problem is when frontend sets it to `None`.
=> Fix traceback caused by None timeout

frontend/coprs_frontend/alembic/versions/bb52d9f878f5_change_webhook_history_timestamp_column_.py, frontend/coprs_frontend/coprs/logic/webhooks_logic.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/coprs/templates/coprs/detail/settings/integrations.html, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py, frontend/coprs_frontend/coprs/views/webhooks_ns/webhooks_general.py
This is part 2 of PR #3342 that implements a table under Settings -> Integration page displaying data from `webhook_history` table. See image below for demo.
=> frontend: show Webhook History under Settings->Integrations

frontend/coprs_frontend/coprs/logic/batches_logic.py
https://docs.sqlalchemy.org/en/20/core/internals.html#sqlalchemy.engine.Dialect.identifier_preparer
fixes traceback:
```
File "/usr/share/copr/coprs_frontend/coprs/logic/batches_logic.py", line 45, in locked_table
_lock_table(table_name)
File "/usr/lib/python3.12/site-packages/backoff/_sync.py", line 105, in retry
ret = target(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/copr/coprs_frontend/coprs/logic/batches_logic.py", line 34, in _lock_table
db.engine.identifier_preparer.quote(table)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'identifier_preparer'
```
=> frontend: add missing dialect ref for identifier_preparer

beaker-tests/DockerTestEnv/Dockerfile, beaker-tests/Sanity/copr-cli-basic-operations/config
-> runtest-modules.sh used old f38 already EOLed chroots
=> beaker: update fedora version to f41 for testing

backend/copr_backend/background_worker_build.py, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/coprs/templates/coprs/copr_dir.repo, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_rpmrepo.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py, frontend/coprs_frontend/tests/test_apiv3/test_rpmrepo.py
Fix #3375
Of course only for Copr projects that has configured to have their storage in Pulp, not all Copr projects.
There are three possible options how to implement this.
1. The Most straightforward is to not generate repofiles ourselves and let Pulp
do it. The downside is that we would have to pass additional parameters (it
is possible though) such as repo priority, module hotfixes attribute, etc,
and figure out how to count repo downloads
2. Generate repofiles ourselves, only point to `baseurl` in Pulp. This IMHO the
best option for keeping compatibility between storage on the backend and in
Pulp, so I implement this option in this PR.
3. Adding a Lighttpd redirect for `baseurl` of the Pulp-stored projects to Pulp
content URL. This will be needed in the future to ensure that users …
=> Point Copr repositories to Pulp

beaker-tests/Sanity/copr-cli-basic-operations/runtest-storage.sh
I wanted a simple test to make sure all of the supported storages work regardless of what storage is configured as default. The coverage is very low and limited only to the most basic workflow (creating a project, building a package, and installing it). That's good enough to know that every storage is configured correctly. I don't want to add any more tests to this script. In case we want a thorough testing of a specific storage, we should change the default storage on copr-fe-dev
DEFAULT_STORAGE = "backend"
and then run the full beaker tests suite.
=> beaker-tests-sanity: run basic tests for every supported storage

rpmbuild/bin/copr-rpmbuild-log
This causes a recursion error, crashing the whole script
File "/usr/lib64/python3.12/logging/__init__.py", line 1762, in callHandlers
hdlr.handle(record)
File "/usr/lib64/python3.12/logging/__init__.py", line 1700, in handle
self.callHandlers(record)
File "/usr/lib64/python3.12/logging/__init__.py", line 1762, in callHandlers
hdlr.handle(record)
File "/usr/lib64/python3.12/logging/__init__.py", line 1695, in handle
maybe_record = self.filter(record)
^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
=> rpmbuild: don't try to log that logger is not ready yet

backend/run/copr-backend-unknown-resalloc-tickets.py
If backend is idle, there are no used tickets - we still want to check for all the taken tickets, and report those.
=> backend: unknown-resalloc-tickets: check tickets taken first

dist-git/copr-dist-git.spec
See #3366
The `check_specfile_matches_repo_name=False` is not available in older versions.
=> distgit: depend on python3-rpkg >= 1.67-4

frontend/coprs_frontend/coprs/forms.py
When supplied with a copr that does not exists the application throws the following warning,
Fixes #1178
=> frontend: Check whether copr:// exists for External Repos in form

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
The commit 609d36988fb307193c77c872b726323bfca0647b only partly resolved the TOCTOU effects (which we are not fixing here either).  The problem being fixed now is that we duplicated the duplication check,
- once in the `validate_on_submit()`, then
- using the `add(check_for_duplicates=True)`. The later check is wrong though, because it raises an exception that is not handled properly (exist_ok=True ignored).
Complements: fdff0c826fe8ffa407f50d4006e617961a6fe046
Complements: 609d36988fb307193c77c872b726323bfca0647b
Fixes: #3471
=> frontend: avoid a duplicated "exists" check

rpmbuild/bin/copr-builder-rhsm-subscribe, rpmbuild/bin/copr-builder-rhsm-subscribe-daemon, rpmbuild/copr-rpmbuild.spec
This allows us to specify RHSM password so it is not visible on `ps aux` output
=> rpmbuild: add copr-builder-rhsm-subscribe script

backend/copr_backend/background_worker_build.py, backend/tests/test_background_worker_build.py, backend/tests/testlib/__init__.py, rpmbuild/bin/copr-builder-ready, rpmbuild/copr-rpmbuild.spec, rpmbuild/copr-rpmbuild.yml, rpmbuild/copr_rpmbuild/config.py
=> Activate Red Hat subscription on demand

frontend/coprs_frontend/coprs/templates/coprs/detail/settings/integrations.html, frontend/coprs_frontend/coprs/views/webhooks_ns/webhooks_general.py
Custom Webhooks are not expected to send a UUID. Instead the UI checks for `None` passed for Webhook UUID and prints "Custom Webhook" instead. See below, 
Fix #3455
=> Custom Webhook now adds a record in Webhook History table

frontend/coprs_frontend/coprs/helpers.py, frontend/coprs_frontend/coprs/logic/complex_logic.py, frontend/coprs_frontend/coprs/repos.py, frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_rpmrepo.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py, frontend/coprs_frontend/tests/test_helpers.py, frontend/coprs_frontend/tests/test_repos.py, frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py
Fix #3446
When a Copr defines a build-time dependency on `copr://foo/bar` and the `foo/bar` project uses Pulp storage, the repository baseurl is now generated correctly.
While the change itself was very simple, I needed to move some code around to avoid circular dependencies.
=> Support build-time dependencies from other storages

rpmbuild/copr-rpmbuild.spec, rpmbuild/tests/test_rhsm.py
Check that we can actually import the script module, and that we call the script with correct arguments.
=> rpmbuild: basic sanity check for rhsm

rpmbuild/copr_rpmbuild/providers/scm.py
=> rpmbuild: make_srpmbuild, set recursive safe.directory

backend/copr_backend/background_worker_build.py, rpmbuild/bin/copr-builder-ready
So it doesn't have an empty stdout when everything went fine, e.g.
```
[2024-10-16 22:31:55,344][  INFO][PID:3774651] Checking that builder machine is OK
[2024-10-16 22:31:56,157][  INFO][PID:3774651] 
[2024-10-16 22:31:56,158][  INFO][PID:3774651] Filling build.info file with builder info
```
=> Add more logging to the copr-builder-ready script

backend/copr_backend/pulp.py
See #3450
This will be necessary for the production Pulp instance. But we still want to keep the possibility of username+password auth for our local development.
=> Allow using crt+key pair for Pulp authentication

rpmbuild/copr-rpmbuild.spec, rpmbuild/copr_rpmbuild/providers/pypi.py
pyp2spec 0.10.0 changed the API around the specfile generation. For fully-automated environments as copr is, the automode newly includes convenient defaults to make the specfiles as close to buildability as possible.
FYI: pyp2spec 0.10.0 is currently in bodhi, so during the next 7 days it'll get to all active Fedoras.
=> Change the pyp2spec invocation

doc/user_documentation/powerful_builders.rst
=> doc: mention powerful builders disk space and admin how to

backend/copr-backend.spec, backend/run/copr-backend-resultdir-cleaner
Build the manual page from an updated --help output.  The logger needs to be initialized in `_main`, otherwise the log-file can mistakenly be created under the `root` user before the `script_requires_user()` check is done.
=> backend: manpage for copr-backend-resultdir-cleaner && logger fix

docker/frontend/files/etc/copr/copr.conf
This is where repodata and RPM packages can be downloaded from
=> docker: point PULP_CONTENT_URL to a local container

misc/copr_new_packages.py
let's discuss this on planning first
=> misc: let's make copr_new_packages a lot faster

frontend/coprs_frontend/tests/test_logic/test_builds_logic.py, rpmbuild/copr_rpmbuild/helpers.py
Fix #3244
It can happen that our builder doesn't understand some architecture macro, e.g. `%{zig_arches}`. In such a case when it is used in `ExclusiveArch`, we shouldn't skip all chroots like we do now. A better approach is to be safe and avoid any skipping. Builds will fail in some chroots that should have been skipped but that can be workarounded by the user by manually submitting the build only for a subset of chroots.
=> Skip only if all macros in ExclusiveArch and ExcludeArch evaluated

docker/distgit/Dockerfile
Otherwise the import command:
copr-distgit-process-import --build-id 7252586 --worker-id import_worker:7252586
Fails with the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lock/copr-dist-git/_@_var_@_lib_@_dist-git_@_cache_@_lookaside_@_pkgs_@_frostyx_@_test-devel_@_copr-cli.lock'
=> docker: create /var/lock/copr-dist-git directory

frontend/coprs_frontend/coprs/logic/actions_logic.py, frontend/coprs_frontend/tests/test_logic/test_builds_logic.py
Fix #3507
The issue was introduced in PR #3330. We previously did this on the backend:
devel = uses_devel_repo(self.front_url, ownername, projectname)
It looks like an unnecessary request, so I am sending the attribute as a part of the action data.
=> Regenerate devel repository when multiple builds are deleted

messaging/copr_messaging/private/hierarchy.py, messaging/copr_messaging/schema.py
=> messaging: summary is missing propery decorator

doc/maintenance/backup_check.rst, doc/maintenance_documentation.rst
=> docs: how to check we backup properly

backend/run/copr-backend-resultdir-cleaner
These are no longer that frequent as we disabled appstream-builder by default long time ago.
Relates: #3495
=> resultdir-cleaner: remove old appstream failures

docker-compose.yaml
version: https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-top-level-element-obsolete
---
link: https://docs.docker.com/engine/network/links/
having link in compose file result in error:
Error response from daemon: bad parameter: link is not supported Error: executing /usr/libexec/docker/cli-plugins/docker-compose up -d: exit status 1
=> docker: remove legacy link and version

frontend/coprs_frontend/pagure_events.py
[ERROR coprs] Textual SQL expression 'LOCK TABLE build IN EXCLU...' should be explicitly declared as text('LOCK TABLE build IN EXCLU...')
=> frontend: use text() wrapper around raw queries

docker/backend/Dockerfile
We don't need the `pulp-cli` tool to upload builds results to Pulp but it is useful for manual queries and debugging if something goes wrong.
=> docker: install pulp-cli to the backend container

backend/conf/copr-be.conf.example
=> backend: typo in the per arch+owner limit option documentation

doc/user_documentation.rst
=> Explain custom chroots

.tito/tito.props
Historically, Tito only modified the Release tag for `--test` builds. Now, we also bump the Version field to ensure that Mock built from Git revisions always has a higher NVR than (previously) released packages.
https://github.com/rpm-software-management/tito/releases/tag/tito-0.6.27-1
=> releng: tito --test builds to have higher NVRs than released versions

backend/copr_backend/background_worker_build.py, backend/copr_backend/storage.py
Otherwise, builds in Pulp projects will fail with this:
Waiting for copr_base repository
Waiting for copr_base repository
Backend process error: Giving up waiting for copr_base repository
So far it worked only because we didn't create Pulp projects directly but rather migrated existing projects into Pulp and therefore this path existed on the backend.
=> Implement a check for every storage whether a repository is available

backend/copr_backend/rpm_builds.py, backend/tests/test_worker_limits.py
Prior this patch, the per-arch limit was applied to all architectures.
Fixes: #3574
=> backend: per-arch/per-owner limit fixed

python/copr/v3/proxies/build_chroot.py
The parameter `chrootname` is mentioned in the docstring but the parameter does not exist in the function.
=> doc: remove non existent parameter from docstring

backend/copr_backend/actions.py, backend/copr_backend/background_worker_build.py, backend/copr_backend/sign.py, backend/run/copr-backend-generate-graphs, backend/run/copr-backend-resultdir-cleaner, backend/run/copr-change-storage, backend/run/copr_find_wrong_chroot_artifacts.py, backend/run/copr_fix_gpg.py, backend/run/copr_print_results_to_delete.py, backend/run/copr_prune_results.py, backend/run/copr_sign_unsigned.py, backend/tests/test_action.py
As recommended in https://peps.python.org/pep-0471/
scandir() has significantly better performance. On some places it does not have sense, but I was doing it everywhere, because it was super easy. I done it, because I recently done the same thing in scancode-toolkit where it matters a lot.
Related: #3601
=> backend: migrate os.listdir() to os.scandir() to increase performance

doc/user_documentation.rst
See #2870
The linked issue was specifically about ppc64le but `%java_arches` is missing on non-EPEL centos-stream-9 and older Fedora versions, so this may be a possible workaround. And also a recipe for users how to deal with similar issues in the future.
=> doc: describe how to have custom macros in the buildroot

.tito/tito.props
The canonical public version identifiers MUST comply with the following scheme:
[N!]N(.N)*[{a|b|rc}N][.postN][.devN]
=> releng: conform --test versions to PEP 440

.github/workflows/auto-merger.yml
PR that meets the following criteria will be automatically merged:
- Passing CI
- Approved by at least one reviewer
- No Draft or WIP title
- No conflicts
The merging workflow runs on schedule every 45 minutes. It can be executed manually on demand from the Actions tab. It internally uses several GitHub Actions to perform the merge.
- https://github.com/redhat-plumbers-in-action/gather-pull-request-metadata to gather PR metadata
- https://github.com/redhat-plumbers-in-action/pull-request-validator to check reviews and CI status
- https://github.com/redhat-plumbers-in-action/auto-merge to perform the merge
- https://github.com/redhat-plumbers-in-action/issue-commentator to comment on PRs about the merge status
---
I have tested the workflow on https://github.com/jamacku/copr/pull/1
A …
=> ci: enable automatic merging of pull requests

frontend/coprs_frontend/coprs/forms.py, frontend/coprs_frontend/coprs/logic/batches_logic.py, frontend/coprs_frontend/tests/request_test_api.py, frontend/coprs_frontend/tests/test_anitya.py, frontend/coprs_frontend/tests/test_apiv3/test_copr_chroot.py, frontend/coprs_frontend/tests/test_apiv3/test_packages.py, frontend/coprs_frontend/tests/test_apiv3/test_project_chroots.py, frontend/coprs_frontend/tests/test_apiv3/test_projects.py, frontend/coprs_frontend/tests/test_comps.py, frontend/coprs_frontend/tests/test_helpers.py, frontend/coprs_frontend/tests/test_logic/test_batch_logic.py, frontend/coprs_frontend/tests/test_logic/test_builds_logic.py, frontend/coprs_frontend/tests/test_logic/test_complex_logic.py, frontend/coprs_frontend/tests/test_logic/test_copr_dirs_logic.py, frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py
=> frontend: stop using deprecated Query.get method

.github/workflows/python-diff-lint.yml
This is needed, e.g., for the dependabot PRs like #3629, where non-privileged user opens PR from a temporary branch in our repository (not a PR from a remote fork).
=> ci: grant permissions to upload sarif data

frontend/coprs_frontend/tests/test_logic/test_batch_logic.py, frontend/coprs_frontend/tests/test_views/test_backend_ns/test_backend_general.py
=> frontend: the function was renamed to get_recorded_queries

backend/tests/test_modifyrepo.py
As openEuler 24.03 LTS upgrad to newer createrepo_c, so should skip this test as well :)
=> backend: fix FTBFS in openEuler 24.03 LTS

frontend/coprs_frontend/coprs/context_processors.py
changes the login menu from 
to
to keep the logins together
Relates to #3483
=> frontend: change order of login menu, sign up should be the latest

rpmbuild/bin/copr-sources-custom
=> rpmbuild: do not rely on working `/bin/su` in chroot

rpmbuild/copr_rpmbuild/helpers.py
Fix #3645
This doesn't ignore the whole (lines of) output. Only the broken characters. In this particular example, there was a problem with the special "u" character in Tina Müller and the output resulted to Tina Mller and Tina M\xfcller. That is much better than failing completely.
=> rpmbuild: ignore unicode errors in the command output

dist-git/copr-dist-git.spec, frontend/copr-frontend.spec
fix: https://github.com/fedora-copr/copr/issues/3637
=> frontend/dist-git: remove redundant byte compile lines, these dirs are empty already

beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh
This test is no longer needed. It was required only in a short transition period when we stopped utilizing MBS to build modules and started relying on our own logic.
And for some reason it started failing with:
rlAssertEquals called without all needed parameters
=> beaker-tests-sanity: remove unnecessary MBS test

frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/logic/packages_logic.py, frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py
=> frontend: use after/with-build-id fields when "rebuilding all"

frontend/coprs_frontend/coprs/templates/_helpers.html, frontend/coprs_frontend/coprs/templates/coprs/detail/_builds_forms.html, frontend/coprs_frontend/coprs/templates/coprs/detail/build.html
Merge after https://github.com/fedora-copr/logdetective-website/pull/207
Fix #3253 
Fix #3583
=> frontend: provide log-detective explain integration for failed builds

doc/custom_source_method.rst, doc/user_documentation.rst
I intentionally keep the explanation out, because it was misleading.  The underlying code generates source RPM itself, and transfers the SRPM to dist-git.   We don't need src.rpm though, hence the https://github.com/release-engineering/dist-git/pull/72  dance.
=> custom method docs fixes

backend/copr-backend.spec, selinux/copr-selinux.spec
In Fedora 42 /usr/bin and /usr/sbin has been merged. We do not have real reason to insist on /usr/sbin and we can do this change for older distributions too.
Fixes: #3635
Addressing:
RPM build warnings:
File listed twice: /usr/bin/copr-assure-permissions
File listed twice: /usr/bin/copr-aws-s3-hitcounter
File listed twice: /usr/bin/copr-backend-analyze-results
File listed twice: /usr/bin/copr-backend-generate-graphs
File listed twice: /usr/bin/copr-backend-process-action
File listed twice: /usr/bin/copr-backend-process-build
File listed twice: /usr/bin/copr-backend-resultdir-cleaner
File listed twice: /usr/bin/copr-backend-service
File listed twice: /usr/bin/copr-backend-unknown-resalloc-tickets.py
File listed twice: /usr/bin/copr-change-storage
File listed twice: …
=> unify bindir and sbindir

frontend/coprs_frontend/coprs/logic/complex_logic.py
This reverts commit https://github.com/fedora-copr/copr/commit/57fcaf089b1a3e6f5f6aa25ebc67f856f996f631.
https://github.com/fedora-copr/copr/pull/3651#issuecomment-2710932004
explains why probably this issue was resolved and we no longer need this
fix. Also this commit caused bad formatting - b' prefix and 'suffix.
If similar issue like https://github.com/fedora-copr/copr/issues/3072 appears, we should probably parse the string
and leave the unparsable characters as their byte value.
See https://github.com/fedora-copr/copr/commit/4c8b3ec5bdc9965def756c95879a451510154cc3
Fix https://github.com/fedora-copr/copr/issues/3644
=> Revert "convert eror message to binary text before emitting" 

frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py
Fedora 43 has a new python3-pygments v2.19 providing slightly different generated code output.
Fixes: #3656
=> frontend: fix code formatting test causing FTBFS

frontend/conf/copr-frontend.sysusers.conf, frontend/copr-frontend.spec
forwarded from downstream copr-frontend with added if-conditions
Related: https://github.com/fedora-copr/copr/issues/2789
=> Add sysusers.d config file to allow rpm to create users/groups automatically

frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py
Addresses concern raised in
https://github.com/fedora-copr/copr/issues/3457#issuecomment-2692289898
Providing nonexisting chroot will result in NoResultFound too.
This change returns 404 instead of 500.
Fix #3457
=> frontend: 404 when build_chroot is not found in database from task_id

frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/pagure_events.py, frontend/coprs_frontend/tests/test_logic/test_copr_dirs_logic.py
This bug caused pagure-events traceback, so any subsequent package
"candidate" (even in project without dots in name) wasn't build either.
=> frontend: pagure-events fail for "dots" in copr.name

rpmbuild/copr-rpmbuild.spec
This package is quite an important connector between the builder and the dist-git server, and worth keeping up2date.
=> rpmbuild: make sure we use the latest dist-git-client

frontend/coprs_frontend/coprs/logic/builds_logic.py, frontend/coprs_frontend/coprs/logic/complex_logic.py, frontend/coprs_frontend/coprs/logic/modules_logic.py, frontend/coprs_frontend/tests/coprs_test_case.py, frontend/coprs_frontend/tests/test_logging.py, frontend/coprs_frontend/tests/test_logic/test_builds_logic.py, frontend/coprs_frontend/tests/test_mail.py, frontend/coprs_frontend/tests/test_pagure_events.py
Since there was a lot of these warnings, there are 3 kind of fixes to these:
- 1st -> Just adds objects created and manipulated in tests to session to silence warnings
- 2nd -> Shifting `db.session.add`: These warnings occur because SQLAlchemy tries to manage relationships affecting an object (e.g. CoprDir) that has not yet been added to the session, and a flush is triggered by some automatic magic inside SQLalchemy, hence the warning. Moving `session.add` before tinkering/adding relationships to it silence the warning
- 3rd -> If for some reason 2nd fix can't be applied due to complicated relationships creations, `no_autoflush` can be applied to tell SQLAlchemy not to automatically flush (we do it anyway with `db.session.flush()`)
The second solution was inspired by …
=> frontend: fix SAWarnings about autoflush

frontend/coprs_frontend/coprs/__init__.py
Per this warning:
coprs/__init__.py:237: DeprecationWarning: 'models_committed' has been moved to 'track_modifications.models_committed'. The top-level import is deprecated and will be removed in Flask-SQLAlchemy 3.1.
=> frontend: models_committed has been moved in sqlalchemy

frontend/coprs_frontend/tests/request_test_api.py
Per DeprecationWarning:
tests/request_test_api.py:26: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
=> frontend: use the new BeautifulSoup find_all() method

doc/how_to_release_copr.rst
=> docs: drop pulp playbooks from RPM releasing manual

rpmbuild/copr_rpmbuild/helpers.py
Slightly inspired by https://github.com/konflux-ci/rpmbuild-pipeline/pull/24
=> rpmbuild: deduplicate two methods

backend/copr_backend/background_worker_build.py
There was an outage when it was rather hard to realize that resalloc API isn't responding.  These new log entries should help with this.  The outage was caused by https://github.com/praiskup/resalloc/issues/173
=> backend: more log "checkpoints" for build worker

docker/frontend/files/etc/copr/copr.conf, frontend/coprs_frontend/coprs/config.py, frontend/coprs_frontend/coprs/models.py, frontend/coprs_frontend/tests/test_repos.py
Close #3632
In Fedora Copr production, we will leave this value as `None` because we want people to use our CDN URLs and basically not even notice, the results moved to Pulp. We already have Lighttpd redirects and everything.
However, in docker-compose, we need to use an URL that is accessible by other containers.
=> Fix local builds in Pulp projects

backend/copr_backend/background_worker_build.py, backend/run/copr-change-storage
This should fix our failing beaker tests and also make sure we won't have inconsistent labels because of leading zeros.
=> Small fixes for Pulp labels

backend/run/copr-pulp-json-to-labels
Before, I only tested the script in my docker container with my local Pulp instance. On both production and STG, we use the Pulp hosted production instance, which has a bit different URLs.
=> backend: pulp in production and STG uses a bit different URLs

backend/run/copr_log_hitcounter.py
This prevents loading 6GB in memory twice.
And replace one assert with a real condition.
Split into three separate commits to ease the review.
=> memory optimalization in copr_log_hitcounter.py

backend/copr_backend/background_worker_build.py, backend/copr_backend/pulp.py, backend/copr_backend/storage.py, backend/run/copr-change-storage
This patch makes the following changes:
PulpClient.create_content() no longer accepts a repository parameter. As a result, the content is uploaded to Pulp without generating an additional task to create a repository version.
PulpClient.add_content() method provides ability to add multiple RPMs to a repository in a single task.
PulpStorage.upload_build_results() method now returns a list of HREFs corresponding to the uploaded RPMs.
PulpStorage.create_repository_version() method now handles creating a new repository version.
The copr-change-storage script now calls PulpStorage.create_repository_version() once for every chroot.
The copr-change-storage script now calls PulpStorage.publish_repository() once for every chroot.
=> Create one repository version and publication per chroot

frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
Fix #3622
This affects only new projects created by the "Create a Fedora Review Project" button. It is completely unrelated to the "Run fedora-review tool for packages in this project" checkbox when creating a new standard project.
=> frontend: disable network when crearing a new fedora review project

backend/copr_backend/pulp.py, backend/copr_backend/storage.py
Pulp Service added a synchronous RPM create API. The new API does not currently support creating labels at upload time. The build id is added to the RPMs in a separate API request.
=> Switches PulpStorage to using the synchronous RPM upload API

backend/tests/test_worker_manager.py
Since we are only checking the length of queue, there's no need for deepcopy the whole test object.
Related https://bugzilla.redhat.com/show_bug.cgi?id=2351386
Fix #3662
=> backend: fix ftbfs for deepcopy not able to handle itertools.count

backend/copr_backend/storage.py
Fix #3689
The 45d1424 commit introduced a small bug. Consider this reproducer:
1. Submit a Copr build that succeeds in several chroots but fails in at least one
2. Click the Delete build button in Copr
For the failed `chroot`, the `resources` is just an empty list. Which IMHO makes sense because we didn't upload any RPMs for that chroot in the first place.
=> backend: fix false-positive failures for build deletion

backend/copr_backend/pulp.py
Prior to this commit, a synchronous upload API was only available in pulp_service plugin. This API has now been released as part of pulp_rpm. This change will ensure COPR continues to be able to upload RPM packages when this API is removed from pulp_service plugin.
=> Switch RPM upload to the synchronous API from pulp_rpm

backend/run/copr-backend-generate-graphs
ParserError: Unknown string format: 2024-10-08T03:07:02.693262+00:00Z
Fixes: #3743
=> backend: drop the 'Z' suffix from timestamp

backend/copr-backend.spec
remove el7 cruft 
and stop using deprecated %py3_build/%py3_install macros
Fixes: RHBZ#2377231
=> backend: Stop using deprecated %py3_build/%py3_install macros

backend/copr_backend/createrepo.py, backend/run/copr-repo
Previously we observed two race conditions.
For #3770, this used to happen:
1. process A adds the `task A` entry to DB
2. process B takes the `task A`, processes it, and commits() it
3. process C lists the task A (due to absence of fair locking!)
4. process A (without lock) detects the `task A` is committed by `process B`, and removes the task from DB to optimize waiting (see #1423 why we do this)
5. process C reads the `task A` content by hgetall(), but receives an empty dict.
Previously we continued, and failed the createrepo run:
6. process C tries to process task A, but fails with KeyError (if this happens, `task B` was already dropped from DB so nobody re-tried).
The problem of #3770 was that `task B` sometimes requested a build removal, but did not finish.  In such case, Frontend …
=> backend: fix race condition in BatchedCreaterepo

frontend/coprs_frontend/coprs/filters.py, frontend/coprs_frontend/coprs/templates/_helpers.html, frontend/coprs_frontend/coprs/templates/coprs/detail/build.html
Ask/Teach AI buttons should be visible only to existing logs, while displaying then immediately when chroot fails.
Fix #3707
Fix #3760
=> frontend: Fix AI button visibility

messaging/copr-messaging.spec
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2377234
=> messaging: Stop using deprecated %py3_build/%py3_install macros

.pylintpath/pylint_copr_plugin.py
This has been deprecated since Python 3.11, and removed from Python 3.13: https://docs.python.org/3/whatsnew/3.13.html#builtins
=> pylint: don't use @classmethod + @property

dist-git/copr-dist-git.spec, keygen/copr-keygen.spec, keygen/setup.py
=> Stop using deprecated %py3_build/%py3_install macros 

common/copr_common/request.py
Otherwise the following tracebacks on distgit
from copr_dist_git.helpers import download_file
url = "https://download.copr-dev.fedorainfracloud.org/results/.../enum-1.1-1.src.rpm"
download_file(url, "/tmp")
Sending data only for POST and PUT is what we have done before f40a284
=> common: send data only for POST and PUT requests

python/copr/v3/proxies/build.py, python/copr/v3/proxies/package.py, python/copr/v3/proxies/project.py, python/copr/v3/proxies/project_chroot.py, python/copr/v3/requests.py
Originally various requests made in v3.proxies.* modules used just GET and POST HTTP methods. However, for some operations these are nowadays deprecated or even already removed based on the APIv3 documentation.
Use PUT and DELETE HTTP requests as required by APIv3 docs instead. Following methods in v3.proxies module have been updated:
* Use DELETE HTTP method:
* BuildProxy.delete: DELETE
* BuildProxy.delete_list: DELETE
* PackageProxy.delete: DELETE
* ProjectProxy.delete: DELETE
* Use PUT HTTP method:
* BuildProxy.cancel: PUT
* PackageProxy.reset: PUT
* ProjectChrootProxy.edit: PUT
* ProjectProxy.edit: PUT
Also define the `DELETE` HTTP method in the `v3.requests` module. 
Doc: https://copr.fedorainfracloud.org/api_3/docs/
Disclaimer: I haven't tested changes manually. In this case I hope …
=> python: Use correctly PUT and DELETE HTTP methods as required by APIv3 docs

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py
Fix #3883
We do the same for `DeleteBuilds` and other routes.
=> frontend: support both POST and DELETE for deleting a build

frontend/coprs_frontend/coprs/filters.py, frontend/coprs_frontend/coprs/templates/_helpers.html, frontend/coprs_frontend/coprs/templates/coprs/detail/build.html
Using the beginning of the build instead of the end of (chroot-)build.
Fix #3847
=> frontend: use beginning of the build as reference for timestamp

backend/copr_backend/background_worker_build.py, backend/copr_backend/pulp.py, backend/copr_backend/storage.py, backend/run/copr-change-storage
While trying to migrate the `@copr/copr-pull-requests` project to Pulp, we
encountered the following error:
Cannot create repository version. More than one rpm.package content with the
duplicate values for name, epoch, version, release, arch, location_href.
This is a common Copr use-case, building a package with the same NEVRA but
different content again and again, so why the error started happening only now?
Everything works perfectly when submitting consequent builds with same NEVRA and
different content because createrepo happens after every build and therefore
Pulp knows it is supposed to remove the old package from the repository and add
the new one.
However, when migrating data using the `copr-change-storage` scrpit, we upload
all the RPM packages and then do createrepo only once …
=> Fix duplicate NEVRA error when migrating projects to Pulp

cli/copr_cli/main.py, frontend/coprs_frontend/coprs/logic/coprs_logic.py, frontend/coprs_frontend/coprs/templates/coprs/_coprs_forms.html, frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py, frontend/coprs_frontend/tests/test_logic/test_coprs_logic.py
Fix https://github.com/fedora-copr/copr/issues/3804
~~not yet tested in stg~~
deployed on stg, the UI seems to be correct. However there is probably no way how to test packit directly against stg instance :/ (but the tests I created passed, so it should behave as expected)
=> frontend, cli: Add wildcard support for 'Packit allowed forge projects'
