cli/copr_cli/main.py

.. and be consistent with webui.  Also fix --help output for
'modify' command.  This complements:
d0dcf9f0b2ab5417903e094e9d362f1bed45c93c

[cli] disable network by default when creating new copr

---

frontend/coprs_frontend/coprs/templates/groups/user_fas_groups.html

This is untested, at least review is needed.

FAS groups need re-login, inform user

---

backend/setup.py
cli/setup.py
common/setup.py
dist-git/setup.py
keygen/setup.py
messaging/setup.py
python/setup.py

- https://pagure.io/copr/copr
+ https://github.com/fedora-copr/copr

Move URL in setup.py files to GitHub homepage

---

.github/copr-build-helpers/changed-packages
backend/copr-backend.spec
beaker-tests/Sanity/copr-cli-basic-operations/files/pkg-no-sources.spec
beaker-tests/Sanity/copr-cli-basic-operations/files/pkg-with-macros.spec
beaker-tests/Sanity/copr-cli-basic-operations/files/test-macros.spec
beaker-tests/Sanity/copr-cli-basic-operations/files/test-timeout.spec
cli/copr-cli.spec
common/python-copr-common.spec
dist-git/copr-dist-git.spec
frontend/copr-frontend.spec
java/copr-java.spec
keygen/copr-keygen.spec
messaging/copr-messaging.spec
python/python-copr.spec
rpmbuild/copr-rpmbuild.spec
selinux/copr-selinux.spec

- https://pagure.io/copr/copr
+ https://github.com/fedora-copr/copr

Move URL tag in specfiles to GitHub home page

---

doc/user_documentation.rst
frontend/coprs_frontend/coprs/logic/coprs_logic.py
frontend/coprs_frontend/coprs/templates/coprs/detail/settings/integrations.html
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
frontend/coprs_frontend/coprs/views/webhooks_ns/webhooks_general.py
frontend/coprs_frontend/tests/test_apiv3/test_coprdirs.py

This would help us with separating build results for pull-requests.

frontend: custom repositories with custom webhook

---

doc/release-notes/2022-11-28.rst
doc/release_notes.rst

doc: add release notes from 2022-11-29

---

selinux/copr.te

selinux: allow httpd_t on copr-frontend to link uploaded files

---

dist-git/run/copr-distgit-process-import

Fix #2391
Created from @praiskup's patch

distgit: mark workers as done

---

doc/release-notes/2022-11-30.rst
doc/release_notes.rst

https://docs.pagure.org/copr.copr/release-notes/2022-11-30.html

doc: add highlights from the 2022-11-30 mini-release

---

backend/copr-backend.spec
cli/copr-cli.spec
common/python-copr-common.spec
dist-git/copr-dist-git.spec
frontend/copr-frontend.spec
frontend/coprs_frontend/coprs/templates/coprs/copr-repo-package.spec
java/copr-java.spec
keygen/copr-keygen.spec
messaging/copr-messaging.spec
mocks/copr-mocks.spec
python/python-copr.spec
rpmbuild/copr-rpmbuild.spec
selinux/copr-selinux.spec

https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1

use spdx license

---

kubernetes/kustomize/distgit.yaml

New distgit pod will share logs between containers.
Distgit is using tcp port 5001.
Signed-off-by: lichaoran <pkwarcraft@gmail.com>

switch distgit to newest container

---

frontend/coprs_frontend/coprs/templates/coprs/detail/_builds_table.html

frontend: fix a jinja2 traceback when displaying a nonexisting batch

---

frontend/coprs_frontend/coprs/templates/project_info.html

this is leftover after our migration to github

link to new homepage

---

kubernetes/kustomize/resalloc.yaml

Persist resalloc database and logs on a pv.
Signed-off-by: lichaoran <pkwarcraft@gmail.com>

add persistent storage for resalloc

---

frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py

frontend: don't let PR builds affect status badges

---

cli/copr_cli/main.py

cli: add options to download only built RPMs/spec files

---

cli/copr_cli/main.py
frontend/coprs_frontend/coprs/forms.py
python/copr/v3/proxies/project.py

frontend, python, cli: hopefully more understandable description

---

.github/workflows/codeql.yml
frontend/coprs_frontend/coprs/logic/packages_logic.py
keygen/src/copr_keygen/__init__.py
keygen/src/copr_keygen/logic.py
keygen/tests/test_handles.py
keygen/tests/test_logic.py

The lgtm.com is now dead, let's migrate to GitHub's built-in code-scanning feature
https://github.blog/2020-09-30-code-scanning-is-now-available/ 
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository

actions: enable code scanning

---

frontend/coprs_frontend/coprs/forms.py
frontend/coprs_frontend/coprs/views/apiv3_ns/__init__.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_packages.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_project_chroots.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
frontend/coprs_frontend/coprs/views/apiv3_ns/json2form.py
frontend/coprs_frontend/tests/test_apiv3/test_project_chroots.py
python/copr/v3/proxies/project_chroot.py

python: fix docs for project_chroot additional_modules option

---

frontend/coprs_frontend/coprs/forms.py

Fix #2482
See https://github.com/wtforms/flask-wtf/pull/479

frontend: WTForms validate function now expect additional parameter

---

frontend/coprs_frontend/coprs/templates/coprs/_coprs_forms.html

frontend: fix typo in basearch example value

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

actions: enable dependabot for our project

---

common/copr_common/dispatcher.py

Many times in the past I wanted to see how exactly the priority queue looks like at a given time but we didn't have a way of doing it. I wanted to implement some script for displaying it, but that's not possible because we AFAIK keep all the priority queue state in a variable (which of course is not accessible from the outside). So what about periodically dumping the queue into a JSON file by the `Dispatcher` itself?
I think this would be good enough for all the times that I needed it in the past but in case it was not sufficient, this would allow us to implement any kind of script to visualize the queue any way we want.

common: periodically dump the priority queue to a JSON file

---

backend/copr_backend/sign.py
backend/tests/test_sign.py

backend: fix chroot version parsing with new python-packaging

---

doc/Makefile
doc/how_to_upgrade_persistent_instances.rst

I had these on my TODO list since the F37 upgrade.

Some documentation changes

---

frontend/coprs_frontend/run/check_for_anitya_version_updates.py

frontend: ignore anitya BadRequest rebuild attempts

---

doc/release-notes/2023-01-25.rst
doc/release_notes.rst

https://docs.pagure.org/copr.copr/release-notes/2023-01-25.html

doc: add 2023-01-25 release notes

---

backend/conf/copr-be.conf.example
backend/copr_backend/actions.py
backend/copr_backend/background_worker_build.py
backend/copr_backend/helpers.py
backend/copr_backend/sign.py
backend/run/copr_fix_gpg.py
backend/run/copr_sign_unsigned.py
backend/tests/test_sign.py

In this PR, we make the gpg key domian name configurable which make rebranding easier :)
Signed-off-by: Li Chaoran <pkwarcraft@gmail.com>

Make sign key domain name configurable

---

frontend/coprs_frontend/coprs/filters.py

frontend: fix build time sorting

---

messaging/copr_messaging/private/hierarchy.py
messaging/copr_messaging/tests/test_schema.py

Related: #2486
Signed-off-by: Ryan Lerch <rlerch@redhat.com>

[messaging] Add app_name property to _CoprMessage base class

---

README.md
backend/docs/source/INSTALL.rst
beaker-tests/Regression/backend/setup.sh
beaker-tests/Regression/dist-git/setup.sh
beaker-tests/Regression/frontend/setup.sh
build_aux/rebuild-copr-stack
build_aux/zuul/pylint-csdiff-script
cli/copr_cli/README.rst
cli/man/copr-cli.cheat
doc/contribute.rst
doc/developer_documentation.rst
doc/downloads.rst
doc/git_guide.rst
doc/how_to_install.rst
doc/index.rst
frontend/coprs_frontend/tests/data/webhooks/diff-01.html
frontend/coprs_frontend/tests/data/webhooks/diff-02.html
java/copr-java.spec
messaging/docs/index.rst
mocks/copr-mocks.spec
python/copr/README.rst
python/docs/installation.rst

some unchanged leftovers from our migration

replacing pagure with github in our projects after copr migration to GH

---

frontend/coprs_frontend/coprs/config.py
frontend/coprs_frontend/coprs/logic/complex_logic.py

frontend: restrict forking of large projects

---

frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py

fix broken rubygem rebuild page.

---

doc/user_documentation.rst

doc: mention all the mass-rebuilding tools that we know of

---

beaker-tests/Sanity/copr-cli-basic-operations/runtest-fedora-review.sh
cli/copr_cli/main.py

cli: add --review parameter for download-build  

---

cli/copr_cli/helpers.py
cli/copr_cli/main.py
cli/tests/resources/get_project_expected.txt
cli/tests/resources/get_project_response.json
cli/tests/test_cli.py

cli: Add `get` command

---

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_general.py

The default KRB5_USER_DENYLIST_PATTERNS=None is not iterable.

frontend: don't 500 for KRB5_USER_DENYLIST_PATTERNS=None

---

cli/man/copr-cli.1.asciidoc

cli: sync --timeout manpage docs with --help output

---

doc/release-notes/2023-04-05.rst

doc: some grammar and format fixes for the 2023-04-05 release notes

---

dist-git/copr_dist_git/package_import.py

so we have some reason why exception appeared

dist-git: improve logging feedback for importing package

---

doc/user_documentation.rst

docs: document [copr-build] keyword

---

doc/user_documentation.rst

doc: update allowed licenses URL from wiki to docs

---

docker/frontend/files/etc/copr/copr.conf
frontend/conf/cron.daily/copr-frontend-optional
frontend/copr-frontend.spec
frontend/coprs_frontend/commands/usage_treemap.py
frontend/coprs_frontend/coprs/config.py
frontend/coprs_frontend/manage.py

frontend: add command for generating usage heatmap

---

cli/man/copr-cli.1.asciidoc

Fix #2173
This is just an additional band-aid for our manpage, eventually we should implement #2634.

cli: describe add-package-custom and edit-package-custom in the manpage

---

beaker-tests/Sanity/copr-cli-basic-operations/build-spec.sh
cli/copr-cli.spec
cli/copr_cli/main.py
cli/tests/test_cli.py
frontend/coprs_frontend/coprs/forms.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py
python/copr/v3/proxies/build.py
python/python-copr.spec

frontend, python, cli: general check if it makes sense to upload SRPM

---

doc/user_documentation.rst

doc: explain that SRPM is downloaded from DistGit only once per build

---

doc/how_to_release_copr.rst
doc/how_to_upgrade_persistent_instances.rst

I started working on PULP playbooks for Copr

doc: adding a pulp instance

---

doc/how_to_upgrade_persistent_instances.rst

doc: add names for the root volumes

---

backend/copr_backend/actions.py
backend/copr_backend/helpers.py
backend/tests/test_action.py

backend: forking: better handle FileExistsError

---

frontend/coprs_frontend/coprs/config.py
frontend/coprs_frontend/coprs/templates/status.html

I wasn't sure where to put the link but this seemed like a good idea.

frontend: show resalloc-webui link in the task queue

---

doc/backup_recovery.rst
doc/maintenance_documentation.rst

doc: add backup recovery page

---

.tito/releasers.conf

tito: stop releasing for F36

---

beaker-tests/DockerTestEnv/Dockerfile
beaker-tests/Sanity/copr-cli-basic-operations/config
beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh

Update tested modules to F38

---

frontend/coprs_frontend/commands/drop_db.py

frontend: request confirmation before deleting db

---

frontend/coprs_frontend/coprs/logic/coprs_logic.py

frontend: don't list temporary projects on main page

---

doc/release-notes/2023-05-25.rst
doc/release_notes.rst

See #2708
https://docs.pagure.org/copr.copr/release-notes/2023-05-25.html

doc: add 2023-05-25 release notes

---

doc/user_documentation.rst

doc: add list of known public Copr instances

---

backend/run/copr_prune_results.py
backend/tests/test_modifyrepo.py

copr_prune_results.py: work-around the arg_max problem

---

backend/copr_backend/helpers.py
backend/run/print_queues.py
common/copr_common/redis_helpers.py
dist-git/copr_dist_git/helpers.py
frontend/coprs_frontend/coprs/helpers.py

Fix: #2743 
Tested on our testing env, will marked as `Ready` when our prod envs are stable :)

add redis auth supported

---

frontend/coprs_frontend/config/copr.conf
frontend/coprs_frontend/coprs/config.py
frontend/coprs_frontend/coprs/logic/packages_logic.py
frontend/coprs_frontend/coprs/templates/homepage_header.html
frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
pylintrc

Fix: #2770 
I just modify our theme and upstream theme, other theme (like redhat copr design) need some modifies as well :)

Add packages count at homepage

---

backend/.readthedocs.yaml
keygen/.readthedocs.yaml
messaging/.readthedocs.yaml
python/.readthedocs.yaml

Add now required .readthedocs.yaml

---

backend/docs/requirements.txt
backend/requirements.txt
keygen/requirements.txt

Follow-up fixes for our readthedocs documentation

---

doc/how_to_rename_chroot.rst
doc/maintenance_documentation.rst
doc/seeddb.rst

For #2702 
This document describe how we rename one of our chroots :)

add how to rename chroot doc

---

python/copr/v3/auth/gssapi.py

python: remove raise_from from future package

---

rpmbuild/copr_distgit_client.py

It is a pity to fail whole build when some random temporary networking issue happens.
Let's use "--connect-timeout", "60" to avoid indefinite hangs on connecting.
Use "--retry", "3", "--retry-all-errors", "--retry-delay", "10" to repeat any download failure.
Observed by a random failure against the texlive package: INFO: Calling: curl -H Pragma: -o logical-markup-utils.doc.tar.xz --location --remote-time --show-error --fail https://src.fedoraproject.org/repo/pkgs/rpms/texlive/logical-markup-utils.doc.tar.xz/sha512/80c44068a6e474071e40a0bf3dc67f0201b21eb84a041fad8423c59c9e34ce138833c54ead638979357dc3026eea55da034daa05e71a56ecabe701ebf53faf24/logical-markup-utils.doc.tar.xz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left …

rpmbuild: retry downloads from lookaside-cache

---

backend/copr_backend/helpers.py
rpmbuild/copr_rpmbuild/automation/rpm_results.py
rpmbuild/copr_rpmbuild/helpers.py

rpmbuild: make sure detected epoch is int() or None

---

rpmbuild/copr-rpmbuild.spec
rpmbuild/copr_rpmbuild/automation/__init__.py
rpmbuild/copr_rpmbuild/automation/rpm_results.py
rpmbuild/copr_rpmbuild/automation/srpm_results.py
rpmbuild/main.py

rpmbuild: more verbose results.json SRPM generator

---

frontend/coprs_frontend/coprs/forms.py
frontend/coprs_frontend/tests/test_forms.py

frontend: allow specifying fully-qualified bootstrap images

---

rpmbuild/copr_rpmbuild/builders/mock.py
rpmbuild/tests/test_mock.py

rpmbuild: build RPM in one mock call

---

rpmbuild/copr_rpmbuild/helpers.py
rpmbuild/mock.cfg.j2

Sorry for multiple unrelated commits in one PR. They are too close to each other and would cause merge conflicts.

Some release-blocker fixes for copr-rpmbuild

---

frontend/coprs_frontend/coprs/logic/builds_logic.py

frontend: skip ExcludeArch and ExclusiveArch for resubmitted builds

---

backend/copr_backend/background_worker_build.py

This should simplify debugging of the Backend <-> Frontend protocol.

backend: dump the /update/ payload to worker.log

---

doc/release-notes/2023-08-16.rst
doc/release_notes.rst

https://docs.pagure.org/copr.copr/release-notes/2023-08-16.html

doc: highlights from 2023-08-16 release

---

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_rpmrepo.py

Follow-up-for: dfd210f1f2fde47488dadcef822e8fe835b5c95a

frontend: provide "priority" value for 'dnf5 copr enable'

---

doc/user_documentation.rst

The list of "forbidden" items started over again from scratch as a new doc page.
Relates: #2681

doc: s/Forbidden/Not-Allowed/ licenses

---

frontend/coprs_frontend/alembic/versions/ec3528516b0c_add_status_reason_column.py
frontend/coprs_frontend/coprs/filters.py
frontend/coprs_frontend/coprs/logic/builds_logic.py
frontend/coprs_frontend/coprs/models.py
frontend/coprs_frontend/coprs/templates/_helpers.html
frontend/coprs_frontend/coprs/templates/coprs/detail/build.html

Explain the reason of skipped chroots

---

behave/features/autospec.feature

I had to bump the package version in dist-git to fix FTBFS.

behave: fix expected version of common

---

frontend/coprs_frontend/coprs/logic/complex_logic.py
frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py

frontend: return empty dict instead of null in API calls to BE

---

backend/copr-backend.spec
backend/copr_backend/background_worker_build.py

Some of the backend tests were broken after merging PR #2920

Fix backend tests

---

backend/run/copr_prune_results.py
backend/tests/test_modifyrepo.py

Recreate missing repodata so that prunerepo doesn't traceback

---

frontend/coprs_frontend/coprs/views/coprs_ns/coprs_builds.py

frontend: don't ignore custom method repos from the WebUI

---

doc/user_documentation.rst

Suggest using the `copr-distgit-client` wrapper by default.

docs: how to work with autospec

---

doc/maintenance/hypervisors.rst
doc/maintenance_documentation.rst

docs: how to maintain Fedora Copr hypervisors

---

beaker-tests/Sanity/copr-cli-basic-operations/files/pkg-with-excludearch.spec
beaker-tests/Sanity/copr-cli-basic-operations/runtest-exclusivearch.sh

Use custom package for testing ExclusiveArch

---

doc/user_documentation.rst

doc: document build timeouts in FAQ

---

doc/maintenance/credentials.rst
doc/maintenance_documentation.rst

docs: Fedora Copr credentials

---

frontend/coprs_frontend/coprs/forms.py
frontend/coprs_frontend/tests/test_forms.py

frontend: allow dot and plus characters in chroot denylist

---

frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py

frontend: show unknown badge when a package has no builds yet

---

frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py

Fix backend/get-build-task for disabled chroots

---

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_packages.py

Fix #3071
For some reason flask-restx internally logs 500 exceptions. Consider the following:
- Route for adding package uses flask-restx, the ApiError (by default 500 error code) logs exception
- The `/packages/list/` route doesn't use flask-restx, and the ApiError doesn't log exception
- The route for getting a single package uses flask-restx, and its ObjectNotFound (404 status code) doesn't log exception.
Which makes me think that flask-restx does this only for 5xx status codes (or possibly only 500) and I didn't find any such thing in our code so I think it does it internally.
In this case, using 4xx status codes makes more sense anyway, so I am switching to them.

frontend: specify 4xx status codes for ApiError exceptions

---

rpmbuild/copr-rpmbuild.spec

install copr-distgit-client with copr-rpmbuild

---

frontend/coprs_frontend/pagure_events.py
frontend/coprs_frontend/tests/lib/pagure_pull_requests.py
frontend/coprs_frontend/tests/test_pagure_events.py

frontend: fix fedora-messaging consumer for the new flask

---

doc/user_documentation/powerful_builders.rst

doc: mention that we support high-performance s390x builders

---

keygen/requirements.txt

keygen: readthedocs works fine with the latest jinja2 now

---

backend/copr-backend.spec
backend/copr_backend/background_worker_build.py
backend/tests/test_background_worker_build.py

backend: periodically check if the resalloc ticket isn't failed

---

frontend/coprs_frontend/coprs/templates/coprs/detail/_builds_forms.html
frontend/coprs_frontend/coprs/templates/coprs/detail/build.html

frontend: add button for feeding log detective

---

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_build_chroots.py
frontend/coprs_frontend/coprs/views/apiv3_ns/schema/fields.py
frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py

frontend: migrate build-chroots to flask-restx

---

beaker-tests/Sanity/copr-cli-basic-operations/build-spec.sh
cli/copr_cli/main.py
frontend/coprs_frontend/coprs/logic/coprs_logic.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py
frontend/coprs_frontend/pagure_events.py

Follow-up-for: abb1bfed77527ee732ed7b5542b5967bba937b12
Fixes: #2786

Don't upload SRPMs/SPECs before the CoprDir is validated

---

doc/release-notes/2024-03-07.rst
doc/user_documentation.rst

doc: mention the SSH access to Copr builders blog post

---

doc/video_tutorial.rst

See https://www.youtube.com/watch?v=cTzXha2N6Xs

doc: link Using Copr CLI - Custom build method video

---

frontend/coprs_frontend/coprs/templates/repositories.html

https://docs.pagure.org/copr.copr/copr_outdated_chroots_removal_policy.html

frontend: add link to the Outdated chroots removal policy

---

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_general.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_modules.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_packages.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_permissions.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_project_chroots.py
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_rpmrepo.py
frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py
frontend/coprs_frontend/coprs/views/misc.py

I suggest to merge this after the release
Fix #3001 #3002 #2999 #2996

frontend: migrate permissions to flask-restx

---

frontend/coprs_frontend/coprs/logic/batches_logic.py

frontend: don't pass raw SQL as string but rather SQLAlchemy text

---

doc/release-notes/2024-04-12.rst
doc/release_notes.rst
frontend/coprs_frontend/commands/clean_expired_projects.py

Also, I've changed the number after how many deleted projects we commit.

Release notes for 2024-04-12

---

beaker-tests/Sanity/copr-cli-basic-operations/runtest-build-batches.sh

beaker-tests-sanity: add tests for build batches

---

doc/video_tutorial.rst

https://www.youtube.com/watch?v=59D_ujWCHlQ

doc: add Copr CLI - Fetching Build Results video

---

frontend/coprs_frontend/coprs/mail.py
frontend/coprs_frontend/tests/test_mail.py

frontend: make EOL chroot emails shorter

---

doc/user_documentation.rst

doc: document that log-out from Ipsilon might help

---

python/docs/client_v3/pagination.rst

Discourage from deleting objects while paginating over them

---

docker/backend_httpd/Dockerfile
docker/database/Dockerfile

Add tag to fetch the images correctly.

docker: Update Dockerfiles for backend_httpd and database

---

doc/video_tutorial.rst

https://www.youtube.com/watch?v=ASSqempxCSI

doc: add Copr CLI - Package Management video

---

cli/copr_cli/main.py
cli/man/copr-cli.1.asciidoc
cli/tests/test_distgit.py
frontend/coprs_frontend/alembic/versions/9fec2c962fcd_create_timeout_per_copr_dir.py
frontend/coprs_frontend/coprs/forms.py
frontend/coprs_frontend/coprs/logic/builds_logic.py
frontend/coprs_frontend/coprs/models.py
frontend/coprs_frontend/coprs/templates/coprs/detail/_package_forms.html
frontend/coprs_frontend/coprs/templates/coprs/detail/package.html
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_packages.py
frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py
frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py

Stop gap measure before #2541 is implemented.
Fix #1591.
Need more testing that I was able to do.

frontend: Add per package timeout option

---

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py
frontend/coprs_frontend/coprs/views/apiv3_ns/schema/schemas.py

Some fixes for deleting builds through API

Fix deleting builds through API

---

doc/user_documentation.rst

doc: document the per-project packages

---

frontend/coprs_frontend/coprs/forms.py

frontend: use package timeout only if it was set

---

backend/copr_backend/background_worker_build.py
rpmbuild/bin/copr-builder

Improve logging for expiring user SSH builders

---

rpmbuild/copr_rpmbuild/automation/fedora_review.py

rpmbuild: Add diff.txt file for fedora review

---

doc/_static/site.css

doc: same color for visited links in the main menu

---

doc/user_documentation.rst

doc: document subprojects aka CoprDirs

---

frontend/coprs_frontend/coprs/forms.py

frontend: do not use six module

---

backend/tests/conftest.py
backend/tests/run/test_copr_prune_results.py
backend/tests/test_action.py

backend: explicitly specify the extractall filter argument

---

cli/copr_cli/main.py
cli/copr_cli/util.py
common/copr_common/compat.py
common/copr_common/request.py
rpmbuild/copr_rpmbuild/helpers.py
rpmbuild/main.py

Replace deprecated pkg_resources with importlib.metadata

---

frontend/coprs_frontend/commands/change_storage.py
frontend/coprs_frontend/coprs/logic/actions_logic.py
frontend/coprs_frontend/manage.py

frontend: add script for changing storage for a project

---

.github/workflows/python-diff-lint.yml

ci: enable Ruff Python linter

---

rpmbuild/copr_rpmbuild/providers/custom.py

rpmbuild: increase the custom method timeout to 90 minutes

---

beaker-tests/DockerTestEnv/Makefile

this changes nothing for docker users

beaker: use podman for testing inside container if installed

---

frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py

frontend: no `app.log` but `app.logger`

---

beaker-tests/DockerTestEnv/Dockerfile
beaker-tests/DockerTestEnv/Makefile
beaker-tests/Sanity/copr-cli-basic-operations/runtest-dnf-copr.sh
beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh
behave/features/steps/builds.py

beaker: migrate to f41

---

README.md
doc/index.rst
frontend/coprs_frontend/coprs/templates/project_info.html

doc: document how to report security issues

---

backend/tests/test_background_worker_build.py
backend/tests/testlib/__init__.py

backend: add test-case for CoprDir's BuildJob.chroot_dir

---

doc/user_documentation.rst

doc: document how to listen Copr messages through Fedora Messaging

---

backend/copr_backend/background_worker_build.py
backend/copr_backend/vm_alloc.py

And enhance the ticket info with the list of requested tags.

backend: add resalloc ticket info to backend.log

---

frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py

frontend: decode bytes to string before sending header as string

---

frontend/coprs_frontend/coprs/logic/outdated_chroots_logic.py

frontend: assume user has been notified by clicking "Expire now" button

---

dist-git/run/prune-dist-git.py
dist-git/setup.py
frontend/coprs_frontend/coprs/logic/complex_logic.py
rpmbuild/copr_rpmbuild/automation/rpm_results.py
rpmbuild/main.py

As recommended in https://peps.python.org/pep-0471/

migrate os.listdir() to os.scandir() to increase performance

---

frontend/copr-frontend.spec
frontend/coprs_frontend/coprs/templates/layout.html
frontend/coprs_frontend/coprs/templates/sponsors.html

frontend: add sponsors of copr project to page footer

---

frontend/coprs_frontend/coprs/logic/coprs_logic.py

<stdin>:1: SAWarning: SELECT statement has a cartesian product between FROM
element(s) "mock_chroot" and FROM element "copr_chroot".
Apply join condition(s) between each element to resolve.

frontend: fix a SQLAlchemy warning

---

frontend/coprs_frontend/coprs/exceptions.py
frontend/coprs_frontend/coprs/logic/packages_logic.py
frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py

frontend: unify error message for rebuild and rebuild all

---

backend/run/copr-change-storage
frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py

Create HTTP redirects for migrated projects

---

frontend/coprs_frontend/coprs/oidc.py

frontend: fix typo in config variable

---

backend/copr_backend/actions.py
common/copr_common/lock.py
common/setup.py
frontend/coprs_frontend/coprs/config.py
frontend/coprs_frontend/coprs/models.py
frontend/coprs_frontend/coprs/templates/coprs/copr_dir.repo
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_rpmrepo.py
frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
frontend/coprs_frontend/tests/test_apiv3/test_rpmrepo.py
frontend/coprs_frontend/tests/test_repos.py

Fix #3632
The whole frontend part of this PR is only a revert of a previously merged change.

Use CDN baseurl for Pulp projects

---

frontend/coprs_frontend/coprs/helpers.py
frontend/coprs_frontend/coprs/logic/complex_logic.py
frontend/coprs_frontend/coprs/mail.py

fix: https://github.com/fedora-copr/copr/issues/3672

frontend: fix FTBFS when using python below 3.12

---

messaging/docs/conf.py

Relates: https://github.com/selectel/pyte/issues/191
Fixes: #3542

messaging: fix FTBFS caused by sphinx config

---

backend/conf/copr-backend.sysusers.conf
backend/copr-backend.spec

forwarded from downstream copr-backend with added if-conditions
Related: #2789

Add sysusers.d config file to allow rpm to create users/groups automatically

---

doc/release-notes/2025-03-26.rst
doc/release_notes.rst

doc: add release notes for copr update

---

frontend/coprs_frontend/coprs/logic/complex_logic.py
frontend/coprs_frontend/coprs/logic/coprs_logic.py
frontend/coprs_frontend/tests/coprs_test_case.py
frontend/coprs_frontend/tests/test_logging.py

frontend: fix autoflushing warnings, take #2

---

backend/copr_backend/storage.py
backend/run/copr-change-storage

Use ThreadPoolExecutor to parallelize RPM uploads to Pulp.

---

backend/copr_backend/pulp.py
backend/copr_backend/storage.py
backend/run/copr-change-storage

Adds build_id pulp_label to RPMs uploaded to Pulp.

---

backend/copr_backend/pulp.py
backend/copr_backend/storage.py

Remove by build id

---

backend/copr_backend/pulp.py
backend/run/copr-pulp-json-to-labels

Add script to migrate pulp.json to Pulp labels

---

doc/conf.py

doc: stop using deprecated get_html_theme_path funciton

---

doc/how_to_upgrade_builders.rst

Absorbing the temporary documentation from here
https://github.com/fedora-copr/copr-image-builder/blob/main/README-bootc.md

Update documentation for builder images to use image-buidler and bootc

---

cli/copr-cli.spec
selinux/copr-selinux.spec

modernize spec file and drop old stuff

---

backend/copr_backend/pulp.py

backend: make sure every PULP api call is logged

---

doc/user_documentation/powerful_builders.rst

docs: add ppcle builders to supported powertful one

---

doc/how_to_upgrade_builders.rst

doc: build OCI images in Konflux

---

common/python-copr-common.spec
common/setup.py
doc/how_to_release_copr.rst
doc/how_to_upgrade_builders.rst
doc/maintenance/development_versions.rst
doc/maintenance_documentation.rst
frontend/copr-frontend.spec
frontend/coprs_frontend/tests/test_views/test_coprs_ns/test_coprs_general.py

And document how to do this in the future.

Fix frontend <-> common dependancy

---

doc/.gitignore
doc/how_to_release_copr.rst
doc/release-notes/2025-08-28.rst
doc/release_notes.rst

Copr release 2025-08-28

---

doc/release-notes/2025-09-17.rst

doc: fix a bulletpoint in the 2025-09-17 release notes

---

backend/conf/copr-be.conf.example
backend/copr_backend/actions.py
backend/copr_backend/daemons/action_dispatcher.py
backend/copr_backend/daemons/build_dispatcher.py
backend/copr_backend/helpers.py
backend/copr_backend/rpm_builds.py
backend/tests/test_config_reader.py
frontend/coprs_frontend/coprs/views/backend_ns/backend_general.py
frontend/coprs_frontend/tests/test_views/test_backend_ns/test_backend_general.py

Don't run builds or actions in projects that are migrated to Pulp

---

doc/release-notes/2025-09-30.rst
doc/release_notes.rst

doc: add 2025-09-30 release notes

---

backend/run/copr-change-storage
frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py

Add option to migrate all projects for an owner

---

doc/how_to_upgrade_builders.rst

doc: upload the golden image howto

---

backend/copr_backend/hitcounter.py

Fix hitcounter auth to frontend

---

frontend/coprs_frontend/coprs/views/misc.py

We are getting 'invalid_scope' for some reason, but I'm unable to reproduce it now. Perhaps if we advise our users to contact us, we'll get a usable user report in the future.
Fixes: #3846

frontend: do not traceback for OAuthError
